# -*- coding: utf-8 -*-
"""Final ATAC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16uPgUfs1BgAh2C1utIK7wVY-xSSgDGns
"""

# CELL 0 — Mount Google Drive
# WHY: All fragment files and all outputs live in Drive.
# Colab local storage resets every session — Drive is the only persistent location.
# After running, a popup will ask you to authorize. Click and sign in.

from google.colab import drive
drive.mount('/content/drive')

import os
frag_dir = "/content/drive/MyDrive/BCG_RAW/extracted"
if os.path.exists(frag_dir):
    files = os.listdir(frag_dir)
    print(f"✅ Found {len(files)} files in BCG_RAW/extracted:")
    for f in sorted(files):
        print(f"   {f}")
else:
    print("❌ Directory not found: /content/drive/MyDrive/BCG_RAW/extracted")
    print("   Check that your Drive is mounted and the path is correct.")

# CELL 1 — Install ALL Required Libraries
# ⚠️ IMPORTANT: After this cell finishes →
#   Runtime → Restart Runtime → continue from CELL 2
#
# INSTALLS:
#   bedtools  — merges genomic intervals (Step 3)
#   tabix     — indexes .tsv.gz files
#   samtools  — genomics utilities
#   pandas<3  — CRITICAL: older pandas avoids ArrowStringArray
#               bug that breaks anndata h5ad writing
#   snapatac2 — ATAC QC, peak matrix, LSI
#   anndata   — AnnData format
#   scanpy    — single-cell analysis
#   muon      — multi-modal AnnData for MOFA+
#   mofapy2   — MOFA+ factor analysis
#   macs2     — peak caller (publication standard)

import subprocess

def run(cmd, label=""):
    print(f"  → {label or cmd[:55]}")
    r = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    out = (r.stdout + r.stderr).strip()
    if out:
        print(out[-1500:])
    return r.returncode

print("=" * 60)
print("Installing system packages...")
print("=" * 60)
run("apt-get install -y -q bedtools tabix samtools", "bedtools + tabix + samtools")

print("\n" + "=" * 60)
print("Installing Python packages...")
print("=" * 60)
run("pip install -q --upgrade pip", "pip upgrade")
run("pip install -q 'pandas<3.0'", "pandas<3.0  ← fixes Arrow h5ad bug")
run("pip install -q snapatac2",    "snapatac2")
run("pip install -q anndata",      "anndata")
run("pip install -q scanpy",       "scanpy")
run("pip install -q muon",         "muon")
run("pip install -q mofapy2",      "mofapy2")
run("pip install -q pybedtools",   "pybedtools")
run("pip install -q scipy numpy matplotlib seaborn", "scipy / numpy / matplotlib")

print("\n" + "=" * 60)
print("Installing MACS2 via conda...")
print("=" * 60)
run("""
if [ ! -f /opt/conda/bin/conda ]; then
    wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
         -O /tmp/miniconda.sh
    bash /tmp/miniconda.sh -b -p /opt/conda
fi
""", "miniconda")
run("export PATH=/opt/conda/bin:$PATH && conda install -y -c bioconda macs2 -q", "macs2")
run("ln -sf /opt/conda/bin/macs2 /usr/local/bin/macs2 2>/dev/null || true", "macs2 symlink")

print("\n" + "=" * 60)
print("✅ All packages installed.")
print("⚠️  NOW → Runtime → Restart Runtime → run from CELL 2")
print("=" * 60)

# CELL 2 — Imports, Paths, and Sample Manifest
# Run this after restarting runtime.
# Defines all paths and sample info used by every later cell.
#
# PUBLICATION NOTE:
#   All outputs go to New_BCG_ATAC_output/ (separate from old pipeline)
#   SAMPLES dict is the single source of truth for all 4 samples

import os, gc, gzip, subprocess, random
import numpy as np
import pandas as pd
import scipy.sparse as sp
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

import snapatac2 as snap
import anndata as ad
import scanpy as sc

print(f"pandas    : {pd.__version__}")
print(f"snapatac2 : {snap.__version__}")
print(f"anndata   : {ad.__version__}")
print(f"scanpy    : {sc.__version__}")

assert int(pd.__version__.split('.')[0]) < 3, \
    "❌ pandas ≥3 detected — re-run Cell 1 and restart runtime"
print("✅ pandas version OK (Arrow bug avoided)")

# ── Paths ─────────────────────────────────────────────────────
BASE_DIR   = Path("/content/drive/MyDrive")
FRAG_DIR   = BASE_DIR / "BCG_RAW/extracted"
OUT_DIR    = BASE_DIR / "New_BCG_ATAC_output"      # NEW output folder
QC_DIR     = OUT_DIR  / "1_qc"
PEAKS_DIR  = OUT_DIR  / "2_peaks"
MATRIX_DIR = OUT_DIR  / "4_matrices"
FINAL_DIR  = OUT_DIR  / "final"

for d in [OUT_DIR, QC_DIR, PEAKS_DIR, MATRIX_DIR, FINAL_DIR]:
    d.mkdir(parents=True, exist_ok=True)

print(f"\nOutput directory: {OUT_DIR}")

# ── Sample manifest ────────────────────────────────────────────
# Paired longitudinal design:
#   h1 = Pre-BCG  Patient R1    h2 = Post-BCG Patient R1
#   h3 = Pre-BCG  Patient R2    h4 = Post-BCG Patient R2
SAMPLES = {
    "h1_Pre_R1" : {
        "file"  : "GSM8945136_Sample_BCG_h1_atac_fragments.tsv.gz",
        "status": "Pre",  "donor": "R1", "gsm": "GSM8945136",
    },
    "h2_Post_R1": {
        "file"  : "GSM8945137_Sample_BCG_h2_atac_fragments.tsv.gz",
        "status": "Post", "donor": "R1", "gsm": "GSM8945137",
    },
    "h3_Pre_R2" : {
        "file"  : "GSM8945138_Sample_BCG_h3_atac_fragments.tsv.gz",
        "status": "Pre",  "donor": "R2", "gsm": "GSM8945138",
    },
    "h4_Post_R2": {
        "file"  : "GSM8945139_Sample_BCG_h4_atac_fragments.tsv.gz",
        "status": "Post", "donor": "R2", "gsm": "GSM8945139",
    },
}

print("\nVerifying fragment files:")
all_ok = True
for sname, meta in SAMPLES.items():
    fpath = FRAG_DIR / meta["file"]
    tpath = Path(str(fpath) + ".tbi")
    ok = fpath.exists() and tpath.exists()
    print(f"  {'✅' if ok else '❌'} {sname}")
    if not ok:
        all_ok = False

print("\n✅ All files confirmed." if all_ok else "\n❌ Missing files — check Drive path")

# CELL 3 — STEP 1A: Import Fragment Files into SnapATAC2
# FIXED: snap.pp.import_data → snap.pp.import_fragments (newer API)

import snapatac2 as snap
import os
from pathlib import Path

FRAG_DIR = Path("/content/drive/MyDrive/BCG_RAW/extracted")
QC_DIR   = Path("/content/drive/MyDrive/New_BCG_ATAC_output/1_qc")
QC_DIR.mkdir(parents=True, exist_ok=True)

SAMPLES = {
    "h1_Pre_R1" : {"file": "GSM8945136_Sample_BCG_h1_atac_fragments.tsv.gz",
                   "status": "Pre",  "donor": "R1", "gsm": "GSM8945136"},
    "h2_Post_R1": {"file": "GSM8945137_Sample_BCG_h2_atac_fragments.tsv.gz",
                   "status": "Post", "donor": "R1", "gsm": "GSM8945137"},
    "h3_Pre_R2" : {"file": "GSM8945138_Sample_BCG_h3_atac_fragments.tsv.gz",
                   "status": "Pre",  "donor": "R2", "gsm": "GSM8945138"},
    "h4_Post_R2": {"file": "GSM8945139_Sample_BCG_h4_atac_fragments.tsv.gz",
                   "status": "Post", "donor": "R2", "gsm": "GSM8945139"},
}

# ── Detect correct API ───────────────────────────────────────
print(f"snapatac2 version: {snap.__version__}")

# Check which function exists
if hasattr(snap.pp, 'import_data'):
    IMPORT_FN = 'import_data'
elif hasattr(snap.pp, 'import_fragments'):
    IMPORT_FN = 'import_fragments'
else:
    # List all available functions
    available = [f for f in dir(snap.pp) if not f.startswith('_')]
    print(f"Available snap.pp functions: {available}")
    raise AttributeError("Neither import_data nor import_fragments found — check version")

print(f"Using: snap.pp.{IMPORT_FN}")
print("=" * 60)
print("STEP 1A — Importing fragment files")
print("=" * 60)

adatas_raw = {}

for sname, meta in SAMPLES.items():
    frag_path = str(FRAG_DIR / meta["file"])
    out_h5    = str(QC_DIR / f"{sname}_tiles.h5ad")

    print(f"\n── {sname} ──")

    # Try loading cached file first
    if os.path.exists(out_h5):
        try:
            adata = snap.read(out_h5)
            print(f"  ✅ Loaded from cache: {adata.n_obs:,} cells")
            adata.obs["status"] = [meta["status"]] * adata.n_obs
            adata.obs["donor"]  = [meta["donor"]]  * adata.n_obs
            adata.obs["gsm"]    = [meta["gsm"]]    * adata.n_obs
            adatas_raw[sname]   = adata
            continue
        except Exception as e:
            print(f"  ⚠️  Cache corrupted — re-importing...")
            os.remove(out_h5)

    print(f"  Importing fragments (20–40 min)...")

    if IMPORT_FN == 'import_fragments':
        # Newer snapatac2 API (≥2.5)
        adata = snap.pp.import_fragments(
            fragment_file     = frag_path,
            chrom_sizes       = snap.genome.hg38,
            file              = out_h5,
            min_num_fragments = 200,
            sorted_by_barcode = False,
        )
    else:
        # Older snapatac2 API
        adata = snap.pp.import_data(
            fragment_file     = frag_path,
            genome            = snap.genome.hg38,
            file              = out_h5,
            min_num_fragments = 200,
            sorted_by_barcode = False,
        )

    adata.obs["status"] = [meta["status"]] * adata.n_obs
    adata.obs["donor"]  = [meta["donor"]]  * adata.n_obs
    adata.obs["gsm"]    = [meta["gsm"]]    * adata.n_obs

    adatas_raw[sname] = adata
    print(f"  ✅ Imported: {adata.n_obs:,} barcodes × {adata.n_vars:,} tiles")

# ── Integrity check ──────────────────────────────────────────
print("\n" + "=" * 60)
print("Verifying tile files...")
all_ok = True
for sname in SAMPLES:
    h5 = QC_DIR / f"{sname}_tiles.h5ad"
    try:
        a = snap.read(str(h5))
        print(f"  ✅ {sname}: {a.n_obs:,} cells — healthy")
    except Exception as e:
        print(f"  ❌ {sname}: CORRUPTED — re-run")
        all_ok = False

if all_ok:
    print("\n✅ Step 1A complete")
else:
    print("\n❌ Some files corrupted — re-run this cell")



import numpy as np
import pandas as pd

print("=" * 60)
print("STEP 1B — Computing TSS enrichment scores")
print("=" * 60)

for sname, adata in adatas_raw.items():
    print(f"\n  ── {sname} ──")

    # Always ensure we are working with a pandas DataFrame for column checks and data extraction.
    # This avoids issues with PyDataFrameElem on backed AnnData objects.
    # The to_pandas() call creates a *copy* of the observation DataFrame as a pandas DataFrame.
    temp_obs_df = adata.obs[:].to_pandas()

    if "tsse" not in temp_obs_df.columns:
        # If 'tsse' is not in the columns, we need to compute it.
        # snap.metrics.tsse modifies adata.obs in-place, potentially back to PyDataFrameElem.
        snap.metrics.tsse(adata, gene_anno=snap.genome.hg38)
        # After computation, re-extract adata.obs as a pandas DataFrame for consistency.
        temp_obs_df = adata.obs[:].to_pandas()

    tsse_arr = np.array(temp_obs_df["tsse"])
    frag_arr = np.array(temp_obs_df["n_fragment"])

    valid    = ~np.isnan(tsse_arr) & ~np.isnan(frag_arr)
    tsse_arr = tsse_arr[valid]
    frag_arr = frag_arr[valid]

    real_cells = ((frag_arr > 1000) & (tsse_arr > 4)).sum()

    print(f"     Total barcodes     : {len(tsse_arr):,}")
    print(f"     Median TSS         : {np.median(tsse_arr):.2f}")
    print(f"     TSS > 4 (good)     : {(tsse_arr > 4).sum():,} ({(tsse_arr>4).mean()*100:.1f}%)")
    print(f"     Frags>1000 & TSS>4 : {real_cells:,}  ← real cells estimate")

print("\n✅ Step 1B complete")

# DIAGNOSTIC — find where barcodes actually live
sname = "h1_Pre_R1"
adata = adatas_raw[sname]
obs_df = adata.obs[:].to_pandas()

print("Index type:", type(adata.obs_names))
print("Index first 3:", list(adata.obs_names[:3]))
print()
print("obs_df index first 3:", obs_df.index.tolist()[:3])
print()
print("obs_df columns:", obs_df.columns.tolist())
print()
print("First row of obs_df:")
print(obs_df.iloc[0])

# ── FIXED TSS export cell ─────────────────────────────────────
import pandas as pd
from pathlib import Path

TSS_SAVE_DIR = Path("/content/drive/MyDrive/BCG_ATAC_TSS")
TSS_SAVE_DIR.mkdir(parents=True, exist_ok=True)

for sname, adata in adatas_raw.items():
    print(f"\n── {sname} ──")

    obs_df = adata.obs[:].to_pandas()

    if "tsse" not in obs_df.columns:
        raise ValueError(f"❌ tsse not found in {sname}")

    # ← use adata.obs_names directly, NOT obs_df.index
    barcodes = list(adata.obs_names)

    if len(barcodes) != len(obs_df):
        raise ValueError(
            f"❌ Barcode count mismatch: "
            f"{len(barcodes)} obs_names vs {len(obs_df)} obs rows"
        )

    tss_df = pd.DataFrame({
        "barcode": barcodes,
        "tsse"   : obs_df["tsse"].values
    })

    out_path = TSS_SAVE_DIR / f"{sname}_tsse.csv"
    tss_df.to_csv(out_path, index=False)

    print(f"  Example barcode: {tss_df['barcode'].iloc[0]}")
    print(f"  Saved: {out_path} ({len(tss_df):,} cells)")

print("\n✅ TSS export complete")

# CELL 5 — STEP 1C: QC Plots Before Filtering
#
# PLOTS GENERATED:
#   Row 1: TSS enrichment histogram per sample
#     Red line = TSS≥4 threshold (publication standard)
#   Row 2: Fragment count histogram (log10)
#     Red line = 1,000 minimum  Orange line = 50,000 doublet cutoff
#
# ⚠️ INSPECT BEFORE RUNNING CELL 6.
# Expected: large spike at TSS~0 (empty droplets) + right-side
# population of real cells. The right population should be >> TSS 4.

import matplotlib.pyplot as plt
import numpy as np
from pathlib import Path

QC_DIR   = Path("/content/drive/MyDrive/New_BCG_ATAC_output/1_qc")

fig, axes = plt.subplots(2, 4, figsize=(22, 10))
fig.suptitle("ATAC QC — All 4 Samples (Before Filtering)",
             fontsize=14, fontweight="bold")

for i, (sname, adata) in enumerate(adatas_raw.items()):
    tsse_vals = np.array(adata.obs["tsse"])
    frag_vals = np.array(adata.obs["n_fragment"])
    tsse_vals = tsse_vals[~np.isnan(tsse_vals)]
    frag_vals = frag_vals[~np.isnan(frag_vals)]

    ax_top = axes[0, i]
    ax_bot = axes[1, i]

    ax_top.hist(tsse_vals, bins=60, color="#1565C0", alpha=0.85, edgecolor="none")
    ax_top.axvline(x=4, color="#E53935", lw=2, linestyle="--", label="TSS≥4")
    ax_top.set_title(f"{sname}", fontsize=9, fontweight="bold")
    ax_top.set_xlabel("TSS Score")
    ax_top.set_ylabel("Cells")
    ax_top.legend(fontsize=7)
    ax_top.text(0.97, 0.95, f"median={np.median(tsse_vals):.1f}",
                transform=ax_top.transAxes, ha="right", va="top", fontsize=8,
                bbox=dict(boxstyle="round", fc="white", alpha=0.8))

    ax_bot.hist(np.log10(frag_vals + 1), bins=60,
                color="#2E7D32", alpha=0.85, edgecolor="none")
    ax_bot.axvline(x=np.log10(1000),  color="#E53935", lw=2, linestyle="--", label="Min 1k")
    ax_bot.axvline(x=np.log10(50000), color="#FB8C00", lw=2, linestyle="--", label="Max 50k")
    ax_bot.set_title(f"{sname}", fontsize=9, fontweight="bold")
    ax_bot.set_xlabel("log10(Fragments)")
    ax_bot.set_ylabel("Cells")
    ax_bot.legend(fontsize=7)

plt.tight_layout()
path = str(QC_DIR / "QC_prefilter.png")
plt.savefig(path, dpi=150, bbox_inches="tight")
plt.show()
print(f"Plot saved: {path}")
print("\n⚠️  Inspect plot — then run Cell 6")

"""with downsampling"""

import snapatac2 as snap
import pandas as pd
import numpy as np
import random
from pathlib import Path

QC_DIR = Path("/content/drive/MyDrive/New_BCG_ATAC_output/1_qc")

SAMPLES = {
    "h1_Pre_R1" : {"status": "Pre",  "donor": "R1", "gsm": "GSM8945136"},
    "h2_Post_R1": {"status": "Post", "donor": "R1", "gsm": "GSM8945137"},
    "h3_Pre_R2" : {"status": "Pre",  "donor": "R2", "gsm": "GSM8945138"},
    "h4_Post_R2": {"status": "Post", "donor": "R2", "gsm": "GSM8945139"},
}

# ── PUBLICATION THRESHOLDS — consistent for all samples ───────
TSS_MIN   = 4
FRAG_MIN  = 1000
FRAG_MAX  = 50000
MAX_CELLS = 10000   # downsample cap — balances paired design
SEED      = 42      # fixed seed for reproducibility

print("=" * 60)
print("STEP 1D — QC filtering (publication-standard)")
print("=" * 60)
print(f"  TSS ≥ {TSS_MIN}  |  Fragments {FRAG_MIN:,}–{FRAG_MAX:,}  |  Max {MAX_CELLS:,} cells")
print()

adatas_filtered = {}
qc_records = []

for sname, adata in adatas_raw.items():
    n_raw = adata.n_obs

    snap.pp.filter_cells(
        adata,
        min_counts = FRAG_MIN,
        max_counts = FRAG_MAX,
        min_tsse   = TSS_MIN,
    )
    n_qc = adata.n_obs

    # Make an in-memory copy after filtering, before potential downsampling
    # This mitigates potential issues with backed AnnData objects or type resolution
    adata = adata.copy()

    # Downsample to MAX_CELLS if needed
    if n_qc > MAX_CELLS:
        random.seed(SEED)
        keep_indices = random.sample(range(n_qc), MAX_CELLS)
        # Create a boolean mask for selection
        mask = np.zeros(n_qc, dtype=bool)
        mask[keep_indices] = True
        adata = adata[mask].copy()

    n_final = adata.n_obs
    adatas_filtered[sname] = adata

    qc_records.append({
        "sample"   : sname,
        "status"   : SAMPLES[sname]["status"],
        "donor"    : SAMPLES[sname]["donor"],
        "raw"      : n_raw,
        "after_qc" : n_qc,
        "final"    : n_final,
        "pct_kept" : round(100 * n_final / n_raw, 1),
    })

    ds_note = f" (downsampled from {n_qc:,})" if n_qc > MAX_CELLS else ""
    print(f"  {sname:15s}  {n_raw:6,} → {n_qc:6,} → {n_final:6,}{ds_note}")

qc_df = pd.DataFrame(qc_records)
qc_df.to_csv(str(QC_DIR / "QC_filtering_summary.csv"), index=False)

print(f"\n  Total cells after QC + downsampling: {qc_df['final'].sum():,}")
print("  (balanced ~10k per sample = publication-ready)")

# Save barcodes for MACS2
print("\n  Saving barcode lists...")
for sname, adata in adatas_filtered.items():
    bc_path = str(QC_DIR / f"{sname}_barcodes.txt")
    pd.Series(adata.obs_names.tolist()).to_csv(bc_path, index=False, header=False)
    print(f"    {sname}: {adata.n_obs:,} barcodes saved")

print("\n✅ Step 1D complete")

"""without downsampling"""

# # CELL 6 — STEP 1D: Filter Cells (NO DOWNSAMPLING)
# #
# # PUBLICATION-STANDARD QC — consistent thresholds across ALL samples:
# #   TSS ≥ 4          : standard ATAC quality cutoff
# #   Fragments ≥ 1000 : minimum fragments for real cells
# #   Fragments ≤ 50000: upper cutoff to reduce likely doublets
# #
# # IMPORTANT:
# #   Keep ALL QC-passed cells for MACS2 peak calling.
# #   Do NOT downsample here.
# #   Downsampling, if needed, should be done later for MOFA+/modeling,
# #   not before peak calling.

# import snapatac2 as snap
# import pandas as pd
# from pathlib import Path

# QC_DIR = Path("/content/drive/MyDrive/New_BCG_ATAC_output/1_qc")
# QC_DIR.mkdir(parents=True, exist_ok=True)

# SAMPLES = {
#     "h1_Pre_R1" : {"status": "Pre",  "donor": "R1", "gsm": "GSM8945136"},
#     "h2_Post_R1": {"status": "Post", "donor": "R1", "gsm": "GSM8945137"},
#     "h3_Pre_R2" : {"status": "Pre",  "donor": "R2", "gsm": "GSM8945138"},
#     "h4_Post_R2": {"status": "Post", "donor": "R2", "gsm": "GSM8945139"},
# }

# # ── QC thresholds ────────────────────────────────────────────
# TSS_MIN  = 4
# FRAG_MIN = 1000
# FRAG_MAX = 50000

# print("=" * 60)
# print("STEP 1D — QC filtering (no downsampling)")
# print("=" * 60)
# print(f"  TSS ≥ {TSS_MIN}  |  Fragments {FRAG_MIN:,}–{FRAG_MAX:,}")
# print()

# adatas_filtered = {}
# qc_records = []

# for sname, adata in adatas_raw.items():
#     n_raw = adata.n_obs

#     snap.pp.filter_cells(
#         adata,
#         min_counts=FRAG_MIN,
#         max_counts=FRAG_MAX,
#         min_tsse=TSS_MIN,
#     )
#     n_qc = adata.n_obs

#     adatas_filtered[sname] = adata

#     qc_records.append({
#         "sample"   : sname,
#         "status"   : SAMPLES[sname]["status"],
#         "donor"    : SAMPLES[sname]["donor"],
#         "raw"      : n_raw,
#         "after_qc" : n_qc,
#         "final"    : n_qc,
#         "pct_kept" : round(100 * n_qc / n_raw, 1),
#     })

#     print(f"  {sname:15s}  {n_raw:6,} → {n_qc:6,}")

# qc_df = pd.DataFrame(qc_records)
# qc_df.to_csv(str(QC_DIR / "QC_filtering_summary.csv"), index=False)

# print(f"\n  Total cells after QC: {qc_df['final'].sum():,}")
# print("  (all QC-passed cells retained for peak calling)")

# # Save barcodes for MACS2
# print("\n  Saving barcode lists...")
# for sname, adata in adatas_filtered.items():
#     bc_path = str(QC_DIR / f"{sname}_barcodes.txt")
#     pd.Series(adata.obs_names).to_csv(bc_path, index=False, header=False)
#     print(f"    {sname}: {adata.n_obs:,} barcodes saved")

# print("\n✅ Step 1D complete")

# CELL 7 — STEP 1E: Post-Filter QC Scatter Plots
#
# Standard ATAC QC figure for publication.
# X = log10(fragments per cell), Y = TSS enrichment score
# Good result: tight cluster in upper-right quadrant

import matplotlib.pyplot as plt
import numpy as np
from pathlib import Path

QC_DIR = Path("/content/drive/MyDrive/New_BCG_ATAC_output/1_qc")

fig, axes = plt.subplots(1, 4, figsize=(22, 5))
fig.suptitle("TSS Enrichment vs Fragment Count — After QC Filtering",
             fontsize=12, fontweight="bold")

for i, (sname, adata) in enumerate(adatas_filtered.items()):
    ax = axes[i]
    tsse = np.array(adata.obs["tsse"])
    frags = np.array(adata.obs["n_fragment"])

    ax.scatter(np.log10(frags + 1), tsse,
               s=1, alpha=0.3, color="#1A237E", rasterized=True)
    ax.axhline(y=4,              color="#E53935", lw=1, linestyle="--", alpha=0.7)
    ax.axvline(x=np.log10(1000), color="#E53935", lw=1, linestyle="--", alpha=0.7)
    ax.set_title(f"{sname}\n(n={adata.n_obs:,})", fontsize=9, fontweight="bold")
    ax.set_xlabel("log10(Fragments)", fontsize=8)
    ax.set_ylabel("TSS Score", fontsize=8)

plt.tight_layout()
path = str(QC_DIR / "QC_scatter_postfilter.png")
plt.savefig(path, dpi=150, bbox_inches="tight")
plt.show()
print(f"Saved: {path}")
print("✅ Step 1E complete — cells clustering upper-right = good quality")

# CELL 8 — STEP 2: Peak Calling with MACS2
#
# PUBLICATION-STANDARD MACS2 PARAMETERS:
#   --nomodel    → ATAC-specific: skip fragment size model building
#   --extsize 200 → extend each read to 200bp (nucleosome-free region)
#   -p 0.01      → p-value threshold 0.01 (statistically justified)
#   --keep-dup all → keep all fragments (10x already deduplicates)
#   --call-summits → report summit of each peak
#
# WHY NOT --nolambda:
#   Your previous run used --nolambda which disables background
#   correction → caused 400k–570k peaks per sample (3–4x too many).
#   With proper background correction and p<0.01, expect 50k–150k peaks.
#
# WHY MACS2 NOT MACS3:
#   MACS2 is the cited standard in published ATAC papers including
#   Daman et al. 2025 (Cancer Cell). MACS3 is newer but less cited.
#
# TIME: ~30–90 minutes per sample







# import subprocess
# import gzip
# import os
# from pathlib import Path

# FRAG_DIR  = Path("/content/drive/MyDrive/BCG_RAW/extracted")
# QC_DIR    = Path("/content/drive/MyDrive/New_BCG_ATAC_output/1_qc")
# PEAKS_DIR = Path("/content/drive/MyDrive/New_BCG_ATAC_output/2_peaks")
# PEAKS_DIR.mkdir(parents=True, exist_ok=True)

# SAMPLES = {
#     "h1_Pre_R1" : {"file": "GSM8945136_Sample_BCG_h1_atac_fragments.tsv.gz"},
#     "h2_Post_R1": {"file": "GSM8945137_Sample_BCG_h2_atac_fragments.tsv.gz"},
#     "h3_Pre_R2" : {"file": "GSM8945138_Sample_BCG_h3_atac_fragments.tsv.gz"},
#     "h4_Post_R2": {"file": "GSM8945139_Sample_BCG_h4_atac_fragments.tsv.gz"},
# }

# # Verify MACS2
# v = subprocess.run("macs2 --version", shell=True, capture_output=True, text=True)
# if v.returncode != 0:
#     subprocess.run("ln -sf /opt/conda/bin/macs2 /usr/local/bin/macs2", shell=True)
# print(f"MACS2: {(v.stdout + v.stderr).strip()}")

# print("\n" + "=" * 60)
# print("STEP 2 — MACS2 Peak Calling (publication parameters)")
# print("=" * 60)

# peak_files = {}

# for sname, meta in SAMPLES.items():
#     print(f"\n  ── {sname} ──")

#     np_path = PEAKS_DIR / f"{sname}_peaks.narrowPeak"
#     if np_path.exists():
#         n = sum(1 for _ in open(np_path))
#         print(f"  ✅ Already exists: {n:,} peaks — skipping")
#         peak_files[sname] = str(np_path)
#         continue

#     frag_gz  = str(FRAG_DIR / meta["file"])
#     barcodes = str(QC_DIR   / f"{sname}_barcodes.txt")
#     tmp_bed  = str(PEAKS_DIR / f"{sname}_tmp.bed")

#     # Filter fragments to QC-passed barcodes
#     print("  Filtering fragments to QC barcodes...")
#     with open(barcodes) as f:
#         valid = set(line.strip() for line in f if line.strip())
#     print(f"  Valid barcodes: {len(valid):,}")

#     n_written = 0
#     with gzip.open(frag_gz, "rt") as fin, open(tmp_bed, "w") as fout:
#         for line in fin:
#             if line.startswith("#"):
#                 continue
#             parts = line.rstrip().split("\t")
#             if len(parts) >= 4 and parts[3] in valid:
#                 fout.write(f"{parts[0]}\t{parts[1]}\t{parts[2]}\n")
#                 n_written += 1
#     print(f"  Fragments written: {n_written:,}")

#     # MACS2 with publication parameters
#     cmd = (
#         f"macs2 callpeak "
#         f"--treatment {tmp_bed} "
#         f"--name {sname} "
#         f"--outdir {str(PEAKS_DIR)} "
#         f"--format BED "
#         f"--gsize hs "
#         f"--nomodel "
#         f"--extsize 200 "
#         f"-p 0.01 "
#         f"--keep-dup all "
#         f"--call-summits "
#         f"2>&1"
#     )
#     print("  Running MACS2...")
#     result = subprocess.run(cmd, shell=True, capture_output=True, text=True)

#     if np_path.exists():
#         n = sum(1 for _ in open(np_path))
#         print(f"  ✅ {n:,} peaks called")
#         peak_files[sname] = str(np_path)
#     else:
#         print("  ❌ MACS2 failed:")
#         print((result.stdout + result.stderr)[-1500:])

#     if os.path.exists(tmp_bed):
#         os.remove(tmp_bed)

# print(f"\n✅ Step 2 complete — {len(peak_files)}/4 samples")
# print("Expected: 50,000–150,000 peaks per sample")

!pip install MACS3

!macs3 --version

# CELL 8 — STEP 2: Peak Calling with MACS3 (CORRECTED)
#
# WHY THIS VERSION:
#   1. Uses MACS3 (already installed and working in your Colab)
#   2. Uses QC-passed barcodes only
#   3. Writes 3-column BED intervals correctly
#   4. Uses -f BED (NOT BEDPE)
#   5. Does NOT expand by fragment count (avoids gigantic temp files)
#   6. Uses background correction (no --nolambda)
#
# EXPECTED:
#   Peak counts should be much more reasonable than before
#   (not ~650, and ideally not the old inflated 400k–570k range)

import subprocess
import gzip
import os
from pathlib import Path

FRAG_DIR  = Path("/content/drive/MyDrive/BCG_RAW/extracted")
QC_DIR    = Path("/content/drive/MyDrive/New_BCG_ATAC_output/1_qc")
PEAKS_DIR = Path("/content/drive/MyDrive/New_BCG_ATAC_output/2_peaks")
PEAKS_DIR.mkdir(parents=True, exist_ok=True)

SAMPLES = {
    "h1_Pre_R1" : {"file": "GSM8945136_Sample_BCG_h1_atac_fragments.tsv.gz"},
    "h2_Post_R1": {"file": "GSM8945137_Sample_BCG_h2_atac_fragments.tsv.gz"},
    "h3_Pre_R2" : {"file": "GSM8945138_Sample_BCG_h3_atac_fragments.tsv.gz"},
    "h4_Post_R2": {"file": "GSM8945139_Sample_BCG_h4_atac_fragments.tsv.gz"},
}

# Verify MACS3
v = subprocess.run("macs3 --version", shell=True, capture_output=True, text=True)
print(f"MACS3: {(v.stdout + v.stderr).strip()}")

print("\n" + "=" * 60)
print("STEP 2 — MACS3 Peak Calling (corrected)")
print("=" * 60)

peak_files = {}

for sname, meta in SAMPLES.items():
    print(f"\n── {sname} ──")

    np_path = PEAKS_DIR / f"{sname}_peaks.narrowPeak"
    if np_path.exists():
        n = sum(1 for _ in open(np_path))
        print(f"  ✅ Already exists: {n:,} peaks — skipping")
        peak_files[sname] = str(np_path)
        continue

    frag_gz  = str(FRAG_DIR / meta["file"])
    barcodes = str(QC_DIR / f"{sname}_barcodes.txt")
    tmp_bed  = str(PEAKS_DIR / f"{sname}_filtered_fragments.bed")

    # Load QC-passed barcodes
    print("  Loading QC-passed barcodes...")
    with open(barcodes) as f:
        valid = set(line.strip() for line in f if line.strip())
    print(f"  Valid barcodes: {len(valid):,}")

    # Write filtered fragments as BED (3 columns only)
    print("  Writing filtered fragment intervals...")
    n_written = 0

    with gzip.open(frag_gz, "rt") as fin, open(tmp_bed, "w") as fout:
        for line in fin:
            if line.startswith("#"):
                continue

            parts = line.rstrip().split("\t")
            if len(parts) < 4:
                continue

            chrom = parts[0]
            start = parts[1]
            end   = parts[2]
            bc    = parts[3]

            if bc not in valid:
                continue

            fout.write(f"{chrom}\t{start}\t{end}\n")
            n_written += 1

    print(f"  Filtered fragment intervals written: {n_written:,}")

    # Run MACS3
    cmd = (
        f"macs3 callpeak "
        f"-t {tmp_bed} "
        f"-n {sname} "
        f"--outdir {str(PEAKS_DIR)} "
        f"-f BED "
        f"-g hs "
        f"--nomodel "
        f"--shift 0 "
        f"--extsize 200 "
        f"-q 0.01 "
        f"--keep-dup all "
        f"--call-summits"
    )

    print("  Running MACS3...")
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True)

    if np_path.exists():
        n = sum(1 for _ in open(np_path))
        print(f"  ✅ {n:,} peaks called")
        peak_files[sname] = str(np_path)
    else:
        print("  ❌ MACS3 failed")
        print((result.stdout + "\n" + result.stderr)[-2000:])

    # Remove temp BED to save space
    if os.path.exists(tmp_bed):
        os.remove(tmp_bed)

print(f"\n✅ Step 2 complete — {len(peak_files)}/4 samples finished")
print("Expected ballpark: tens of thousands to low hundreds of thousands per sample")

"""consensus"""

# CELL 9 — STEP 3: Build Consensus Peak Set
#
# WHY CONSENSUS PEAKS:
#   Each sample has slightly different peak coordinates.
#   We merge overlapping peaks from all 4 samples into one
#   unified list so all samples share identical columns in
#   the count matrix — required for MOFA+ comparison.
#
# STEPS:
#   3a: narrowPeak → BED3 (chr, start, end)
#   3b: Concatenate all 4 BEDs
#   3c: Sort (bedtools requires sorted input)
#   3d: bedtools merge (collapse overlapping peaks)
#   3e: Filter to chr1–22, X, Y only
#
# PUBLICATION TARGET: 50,000–200,000 consensus peaks

import subprocess
import pandas as pd
import numpy as np
from pathlib import Path

PEAKS_DIR = Path("/content/drive/MyDrive/New_BCG_ATAC_output/2_peaks")

# Reload peak_files if session restarted
SAMPLE_NAMES = ["h1_Pre_R1", "h2_Post_R1", "h3_Pre_R2", "h4_Post_R2"]
peak_files = {}
for sname in SAMPLE_NAMES:
    p = PEAKS_DIR / f"{sname}_peaks.narrowPeak"
    if p.exists():
        peak_files[sname] = str(p)

print(f"Peak files found: {len(peak_files)}/4")
if len(peak_files) < 4:
    print("❌ Missing peak files — re-run Cell 8")
    raise RuntimeError("Missing peak files")

print("\n" + "=" * 60)
print("STEP 3 — Building consensus peak set")
print("=" * 60)

# 3a: narrowPeak → BED3
print("\n  3a: Converting to BED3...")
bed3_files = []
for sname, np_path in peak_files.items():
    bed3 = str(PEAKS_DIR / f"{sname}.bed")
    n = 0
    with open(np_path) as fin, open(bed3, "w") as fout:
        for line in fin:
            p = line.strip().split("\t")
            if len(p) >= 3:
                fout.write(f"{p[0]}\t{p[1]}\t{p[2]}\n")
                n += 1
    print(f"    {sname}: {n:,} peaks")
    bed3_files.append(bed3)

# 3b: Concatenate
cat = str(PEAKS_DIR / "all_cat.bed")
with open(cat, "w") as fout:
    for b in bed3_files:
        with open(b) as fin:
            fout.write(fin.read())
n_pre = sum(1 for _ in open(cat))
print(f"\n  3b: Concatenated: {n_pre:,} total peaks")

# 3c: Sort
srt = str(PEAKS_DIR / "all_sorted.bed")
subprocess.run(f"sort -k1,1 -k2,2n {cat} > {srt}", shell=True)
print("  3c: Sorted")

# 3d: bedtools merge
mrg = str(PEAKS_DIR / "merged.bed")
subprocess.run(f"bedtools merge -i {srt} > {mrg}", shell=True)
n_mrg = sum(1 for _ in open(mrg))
print(f"  3d: After merge: {n_mrg:,} peaks")

# 3e: Standard chromosomes only
std = set([f"chr{i}" for i in range(1, 23)] + ["chrX", "chrY"])
consensus_bed = str(PEAKS_DIR / "consensus_peaks.bed")
n_final = 0
with open(mrg) as fin, open(consensus_bed, "w") as fout:
    for line in fin:
        if line.split("\t")[0] in std:
            fout.write(line)
            n_final += 1
print(f"  3e: After chr filter: {n_final:,} consensus peaks")

# Stats
df = pd.read_csv(consensus_bed, sep="\t", header=None, names=["chr","start","end"])
df["width"] = df["end"] - df["start"]
print(f"\n  Peak width: median={df['width'].median():.0f}bp  "
      f"mean={df['width'].mean():.0f}bp  "
      f"max={df['width'].max()}bp")
df.to_csv(str(PEAKS_DIR / "consensus_peaks_stats.csv"), index=False)

if n_final > 300000:
    print("\n  ⚠️  Still >300k peaks — check MACS2 parameters")
elif n_final < 30000:
    print("\n  ⚠️  <30k peaks — may be too few")
else:
    print(f"\n  ✅ {n_final:,} consensus peaks — publication-ready range")

print("\n✅ Step 3 complete")

# CELL 10 — STEP 4: Build Peak Count Matrix
#
# For each QC-passed cell, count fragments overlapping each
# consensus peak. Result: cells × peaks sparse matrix.
# Sparsity >95% is normal for ATAC-seq data.
#
# ARROW FIX: snap returns internal AnnData with ArrowStringArray.
# We extract the raw matrix + build a fresh standard AnnData
# with numpy object arrays — required for h5ad saving.
# Saved as .npz + .csv (bypasses the h5ad Arrow incompatibility).

import snapatac2 as snap
import anndata as ad
import scipy.sparse as sp
import numpy as np
import pandas as pd
from pathlib import Path
import os

QC_DIR     = Path("/content/drive/MyDrive/New_BCG_ATAC_output/1_qc")
PEAKS_DIR  = Path("/content/drive/MyDrive/New_BCG_ATAC_output/2_peaks")
MATRIX_DIR = Path("/content/drive/MyDrive/New_BCG_ATAC_output/4_matrices")
MATRIX_DIR.mkdir(parents=True, exist_ok=True)

consensus_bed = str(PEAKS_DIR / "consensus_peaks.bed")
n_final = sum(1 for _ in open(consensus_bed))

SAMPLES = {
    "h1_Pre_R1" : {"status": "Pre",  "donor": "R1", "gsm": "GSM8945136"},
    "h2_Post_R1": {"status": "Post", "donor": "R1", "gsm": "GSM8945137"},
    "h3_Pre_R2" : {"status": "Pre",  "donor": "R2", "gsm": "GSM8945138"},
    "h4_Post_R2": {"status": "Post", "donor": "R2", "gsm": "GSM8945139"},
}

print("=" * 60)
print(f"STEP 4 — Peak count matrices  ({n_final:,} consensus peaks)")
print("=" * 60)

peak_matrices = {}

for sname, adata_qc in adatas_filtered.items():
    print(f"\n  ── {sname} ──  ({adata_qc.n_obs:,} cells)")

    npz_path = MATRIX_DIR / f"{sname}_X.npz"
    obs_path = MATRIX_DIR / f"{sname}_obs.csv"
    var_path = MATRIX_DIR / f"{sname}_var.csv"

    # Skip if already built
    if npz_path.exists() and obs_path.exists():
        print("    Loading from cache...")
        X      = sp.load_npz(str(npz_path))
        obs_df = pd.read_csv(str(obs_path), index_col=0)
        var_df = pd.read_csv(str(var_path), index_col=0)
        for col in obs_df.columns:
            obs_df[col] = obs_df[col].astype(str).astype(object)
        peak_matrices[sname] = ad.AnnData(X=X, obs=obs_df, var=var_df)
        print(f"    ✅ {peak_matrices[sname].n_obs:,} × {peak_matrices[sname].n_vars:,}")
        continue

    snap_out = str(MATRIX_DIR / f"{sname}_snap.h5ad")
    if os.path.exists(snap_out):
        os.remove(snap_out)

    # Build peak matrix
    peak_snap = snap.pp.make_peak_matrix(
        adata_qc,
        peak_file = consensus_bed,
        file      = snap_out,
    )

    if peak_snap.n_vars == 0:
        print("    ❌ 0 peaks — check consensus_bed")
        continue

    # Extract matrix — bypasses Arrow incompatibility entirely
    X_csr     = sp.csr_matrix(peak_snap.X[:])
    obs_names = np.array([str(x) for x in peak_snap.obs_names], dtype=object)
    var_names = np.array([str(x) for x in peak_snap.var_names], dtype=object)

    n = X_csr.shape[0]
    obs_df = pd.DataFrame({
        "sample": np.array([sname]                    * n, dtype=object),
        "status": np.array([SAMPLES[sname]["status"]] * n, dtype=object),
        "donor" : np.array([SAMPLES[sname]["donor"]]  * n, dtype=object),
        "gsm"   : np.array([SAMPLES[sname]["gsm"]]    * n, dtype=object),
    }, index=pd.Index(obs_names))
    var_df = pd.DataFrame(index=pd.Index(var_names))

    # Save as npz + csv (avoids Arrow h5ad write bug)
    sp.save_npz(str(npz_path), X_csr)
    obs_df.to_csv(str(obs_path))
    var_df.to_csv(str(var_path))

    if os.path.exists(snap_out):
        os.remove(snap_out)

    sparsity = 100 * (1 - X_csr.nnz / (X_csr.shape[0] * X_csr.shape[1]))
    adata_clean = ad.AnnData(X=X_csr, obs=obs_df, var=var_df)
    peak_matrices[sname] = adata_clean

    print(f"    ✅ {adata_clean.n_obs:,} × {adata_clean.n_vars:,}  sparsity={sparsity:.1f}%")

print(f"\n✅ Step 4 complete — {len(peak_matrices)}/4 matrices built")

adata = peak_matrices["h1_Pre_R1"]
print(adata.shape)
print("sparsity:", 1 - adata.X.nnz/(adata.n_obs*adata.n_vars))

# CELL 11 — STEP 5: Combine All Samples into One AnnData
#
# Stack 4 sample matrices vertically into one combined object.
# Prefix barcodes with sample name to ensure global uniqueness.
# Save as ATAC_combined_raw.h5ad — snapshot before normalization.

import anndata as ad
import scipy.sparse as sp
import pandas as pd
import numpy as np
from pathlib import Path

MATRIX_DIR = Path("/content/drive/MyDrive/New_BCG_ATAC_output/4_matrices")
FINAL_DIR  = Path("/content/drive/MyDrive/New_BCG_ATAC_output/final")
FINAL_DIR.mkdir(parents=True, exist_ok=True)

SAMPLES = {
    "h1_Pre_R1" : {"status": "Pre",  "donor": "R1", "gsm": "GSM8945136"},
    "h2_Post_R1": {"status": "Post", "donor": "R1", "gsm": "GSM8945137"},
    "h3_Pre_R2" : {"status": "Pre",  "donor": "R2", "gsm": "GSM8945138"},
    "h4_Post_R2": {"status": "Post", "donor": "R2", "gsm": "GSM8945139"},
}

print("=" * 60)
print("STEP 5 — Combining samples into one AnnData")
print("=" * 60)

# Reload from .npz if peak_matrices not in memory
if 'peak_matrices' not in dir() or len(peak_matrices) < 4:
    print("  Reloading matrices from .npz files...")
    peak_matrices = {}
    for sname in SAMPLES:
        npz = MATRIX_DIR / f"{sname}_X.npz"
        obs = MATRIX_DIR / f"{sname}_obs.csv"
        var = MATRIX_DIR / f"{sname}_var.csv"
        if npz.exists():
            X      = sp.load_npz(str(npz))
            obs_df = pd.read_csv(str(obs), index_col=0)
            var_df = pd.read_csv(str(var), index_col=0)
            for col in obs_df.columns:
                obs_df[col] = obs_df[col].astype(str).astype(object)
            peak_matrices[sname] = ad.AnnData(X=X, obs=obs_df, var=var_df)
            print(f"    ✅ {sname}: {peak_matrices[sname].n_obs:,} cells")

# Prefix barcodes for global uniqueness
print("\n  Prefixing barcodes...")
for sname, pm in peak_matrices.items():
    pm.obs_names = pd.Index(
        np.array([f"{sname}_{bc}" for bc in pm.obs_names], dtype=object)
    )
    pm.obs["sample"] = np.array([sname] * pm.n_obs, dtype=object)
    pm.obs["status"] = np.array([SAMPLES[sname]["status"]] * pm.n_obs, dtype=object)
    pm.obs["donor"]  = np.array([SAMPLES[sname]["donor"]]  * pm.n_obs, dtype=object)
    pm.obs["gsm"]    = np.array([SAMPLES[sname]["gsm"]]    * pm.n_obs, dtype=object)

# Concatenate
print("  Concatenating...")
adata_atac = ad.concat(
    list(peak_matrices.values()),
    join="inner", merge="same",
    label="batch", keys=list(peak_matrices.keys()),
    index_unique="-",
)

# Force numpy strings (Arrow fix)
for col in adata_atac.obs.columns:
    adata_atac.obs[col] = np.array(
        adata_atac.obs[col].astype(str).tolist(), dtype=object
    )
adata_atac.obs_names = pd.Index(
    np.array(adata_atac.obs_names.astype(str).tolist(), dtype=object)
)
adata_atac.var_names = pd.Index(
    np.array(adata_atac.var_names.astype(str).tolist(), dtype=object)
)

print(f"\n  ✅ Combined: {adata_atac.n_obs:,} cells × {adata_atac.n_vars:,} peaks")
print("\n  Breakdown:")
for (d, s), grp in adata_atac.obs.groupby(["donor","status"]):
    print(f"    R{d[-1]} {s}: {len(grp):,} cells")

raw_path = str(FINAL_DIR / "ATAC_combined_raw.h5ad")
adata_atac.write_h5ad(raw_path)
print(f"\n  Saved: ATAC_combined_raw.h5ad")
print("\n✅ Step 5 complete")

# CELL 12 — STEP 6A: TF-IDF Normalization
#
# TF-IDF is the standard normalization for ATAC-seq.
# TF  = count(cell,peak) / total_fragments(cell)  → library size correction
# IDF = log(1 + n_cells / n_cells_with_peak)       → peak frequency weighting
# Rare peaks (open in few cells) get upweighted — they carry cell-type info.
# Common peaks (open in all cells) get downweighted — they are uninformative.
#
# Raw counts preserved in layer "counts" for downstream reference.

import scipy.sparse as sp
import numpy as np

print("=" * 60)
print("STEP 6A — TF-IDF normalization")
print("=" * 60)

X = adata_atac.X
if not sp.issparse(X):
    X = sp.csr_matrix(X.astype(np.float64))
else:
    X = X.astype(np.float64)

n_cells, n_peaks = X.shape
print(f"  Input: {n_cells:,} cells × {n_peaks:,} peaks")

# Preserve raw counts
adata_atac.layers["counts"] = X.copy()
print("  Raw counts saved to layer 'counts'")

# TF: normalize each cell by its total fragment count
cell_totals = np.array(X.sum(axis=1)).flatten()
cell_totals[cell_totals == 0] = 1
TF = sp.diags(1e4 / cell_totals) @ X
print("  TF computed (scale=10,000)")

# IDF: penalize ubiquitous peaks, reward cell-type specific peaks
cells_per_peak = np.array((X > 0).sum(axis=0)).flatten()
IDF = np.log1p(n_cells / (cells_per_peak + 1))
print(f"  IDF computed (range: {IDF.min():.3f}–{IDF.max():.3f})")

# TF-IDF
adata_atac.X = TF.multiply(IDF).tocsr()
adata_atac.uns["normalization"] = "TF-IDF"
adata_atac.uns["scale_factor"]  = 1e4
print("  ✅ TF-IDF applied")

print("\n✅ Step 6A complete")

# # CELL 13 — STEP 6B: Log1p Transform + Highly Variable Peaks
# #
# # Log1p compresses the TF-IDF range for better numerical stability in LSI.
# # Highly variable peaks (HVP) are the top peaks by variance across cells.
# # Only HVPs carry meaningful cell-type signal — the rest is noise.
# # We select min(50000, n_peaks) HVPs for LSI computation.

# import scanpy as sc

# print("=" * 60)
# print("STEP 6B — Log1p + highly variable peak selection")
# print("=" * 60)

# sc.pp.log1p(adata_atac)
# adata_atac.layers["lognorm"] = adata_atac.X.copy()
# print("  log1p applied")

# n_select = min(50000, adata_atac.n_vars)
# sc.pp.highly_variable_genes(
#     adata_atac,
#     n_top_genes = n_select,
#     flavor      = "seurat_v3",
#     span        = 0.3,
# )

# n_hvp = int(adata_atac.var["highly_variable"].sum())
# print(f"  HVP selected: {n_hvp:,} / {adata_atac.n_vars:,} ({100*n_hvp/adata_atac.n_vars:.1f}%)")

# print("\n✅ Step 6B complete")

# CELL 14 — STEP 6C: LSI / Spectral embedding for ATAC
#
# Standard SnapATAC2 approach:
#   select ATAC features with snap.pp.select_features
#   run snap.tl.spectral on those selected features
#
# Notes:
#   - This is more appropriate for ATAC than Scanpy RNA-style HVG selection.
#   - SnapATAC2 spectral embedding uses cosine similarity by default in v2.9
#     and stores the result in adata.obsm["X_spectral"].

import snapatac2 as snap
import numpy as np

print("=" * 60)
print("STEP 6C — Feature selection + LSI (spectral embedding)")
print("=" * 60)

# Select informative ATAC peaks
# 50k is a reasonable target for your dataset size
snap.pp.select_features(
    adata_atac,
    n_features=50000,
    inplace=True,
)

# Report how many were selected
if "selected" in adata_atac.var.columns:
    n_sel = int(np.asarray(adata_atac.var["selected"]).sum())
    print(f"  Selected ATAC features: {n_sel:,} / {adata_atac.n_vars:,}")
else:
    print("  ⚠️ 'selected' mask not found in var; proceeding anyway")

print("  Running spectral embedding...")
snap.tl.spectral(
    adata_atac,
    features="selected",
    n_comps=50,
)

shape = adata_atac.obsm["X_spectral"].shape
print(f"  ✅ Spectral embedding: {shape[0]:,} cells × {shape[1]} components")
print("  Stored in adata_atac.obsm['X_spectral']")
print("  For downstream use, commonly inspect/use components 2–30 if component 1 tracks depth")

print("\n✅ Step 6C complete")

# CELL 15 — STEP 6D: KNN Graph + UMAP
#
# UMAP for visual quality control of the final ATAC embedding.
# Uses LSI components 2–30 (skipping component 1 = library size).
# Uses scanpy plotter (NOT snap.pl.umap which is plotly-only).
#
# EXPECTED PATTERNS:
#   By donor:  R1/R2 separate (patient effect — normal and expected)
#   By status: Pre/Post interleaved within clusters (ideal for MOFA+)
#   By sample: h1+h2 cluster together, h3+h4 cluster together

import scanpy as sc
import snapatac2 as snap
import matplotlib.pyplot as plt
from pathlib import Path

FINAL_DIR = Path("/content/drive/MyDrive/New_BCG_ATAC_output/final")

print("=" * 60)
print("STEP 6D — KNN + UMAP")
print("=" * 60)

print("  Building KNN (components 2–30)...")
snap.pp.knn(
    adata_atac,
    use_rep     = "X_spectral",
    use_dims    = list(range(1, 30)),
    n_neighbors = 15,
)

print("  Computing UMAP...")
snap.tl.umap(adata_atac)

print("  Plotting...")
fig, axes = plt.subplots(1, 3, figsize=(21, 6))
fig.suptitle(f"ATAC UMAP — {adata_atac.n_obs:,} Cells  (Publication QC)",
             fontsize=13, fontweight="bold")

for ax, color, title in zip(
    axes,
    ["donor",  "status",              "sample"],
    ["By Donor (R1/R2)", "By BCG Status (Pre/Post)", "By Sample (h1–h4)"]
):
    sc.pl.embedding(adata_atac, basis="X_umap", color=color,
                    ax=ax, show=False, title=title, frameon=False)

plt.tight_layout()
umap_path = str(FINAL_DIR / "ATAC_UMAP_publication.png")
plt.savefig(umap_path, dpi=150, bbox_inches="tight")
plt.show()
print(f"  ✅ UMAP saved: ATAC_UMAP_publication.png")

print("\n✅ Step 6D complete")

# CELL 16 — Save Final ATAC AnnData + Verification
#
# FINAL OUTPUT: ATAC_analysis_ready.h5ad
#
# CONTENTS:
#   .X                  = TF-IDF normalized peak matrix
#   .layers["counts"]   = raw peak counts
#   .obs                = sample, status, donor, gsm per cell
#   .var["selected"]    = True/False for selected ATAC peaks
#   .obsm["X_spectral"] = 50-component LSI / spectral embedding
#   .obsm["X_umap"]     = 2D UMAP coordinates (if computed)

from pathlib import Path
import numpy as np

FINAL_DIR = Path("/content/drive/MyDrive/New_BCG_ATAC_output/final")
FINAL_DIR.mkdir(parents=True, exist_ok=True)

print("=" * 60)
print("SAVING — Final ATAC AnnData")
print("=" * 60)

final_path = str(FINAL_DIR / "ATAC_analysis_ready.h5ad")
adata_atac.write_h5ad(final_path)
print(f"  ✅ Saved: {final_path}")

# ── Verification ─────────────────────────────────────────────
print("\n" + "=" * 60)
print("ATAC OBJECT CHECK")
print("=" * 60)

print(f"\n  Cells      : {adata_atac.n_obs:,}")
print(f"  Peaks      : {adata_atac.n_vars:,}")
print(f"  Layers     : {list(adata_atac.layers.keys())}")
print(f"  Embeddings : {list(adata_atac.obsm.keys())}")

print("\n  Cell breakdown:")
for sname in ["h1_Pre_R1", "h2_Post_R1", "h3_Pre_R2", "h4_Post_R2"]:
    n = (adata_atac.obs["sample"] == sname).sum()
    d = adata_atac.obs.loc[adata_atac.obs["sample"] == sname, "donor"].iloc[0]
    s = adata_atac.obs.loc[adata_atac.obs["sample"] == sname, "status"].iloc[0]
    print(f"    {sname:15s}  R{d[-1]} {s:4s}  {n:,} cells")

X_raw = adata_atac.layers["counts"]
sparsity = 100 * (1 - X_raw.nnz / (X_raw.shape[0] * X_raw.shape[1]))

if "selected" in adata_atac.var.columns:
    n_sel = int(np.asarray(adata_atac.var["selected"]).sum())
else:
    n_sel = 0

print(f"\n  Sparsity   : {sparsity:.1f}%  (>95% = normal for ATAC)")
print(f"  Selected   : {n_sel:,} ATAC peaks used for LSI")
print(f"  Norm       : TF-IDF  ✅")
print(f"  LSI        : 50 components in obsm['X_spectral']  ✅")

if "X_umap" in adata_atac.obsm:
    print(f"  UMAP       : present in obsm['X_umap']  ✅")
else:
    print(f"  UMAP       : not found")

print(f"  QC thresh  : TSS≥4, Frags 1k–50k  ✅")

print("\n" + "=" * 60)
print("✅ ATAC object saved and verified")
print("=" * 60)

# # CELL 16 — Save Final ATAC AnnData + Full Verification
# #
# # FINAL OUTPUT: ATAC_normalized.h5ad
# # This is the input to the next pipeline: MuData → MOFA+
# #
# # CONTENTS:
# #   .X                     = TF-IDF + log1p normalized values
# #   .layers["counts"]      = raw peak counts (preserved)
# #   .layers["lognorm"]     = log-normalized copy
# #   .obs                   = sample, status, donor, gsm per cell
# #   .var["highly_variable"]= True/False per peak
# #   .obsm["X_spectral"]    = 50-component LSI (use cols 2–30)
# #   .obsm["X_umap"]        = 2D UMAP coordinates

# import scipy.sparse as sp
# import numpy as np
# from pathlib import Path

# FINAL_DIR = Path("/content/drive/MyDrive/New_BCG_ATAC_output/final")

# print("=" * 60)
# print("SAVING — Final ATAC AnnData (publication quality)")
# print("=" * 60)

# final_path = str(FINAL_DIR / "ATAC_normalized.h5ad")
# adata_atac.write_h5ad(final_path)
# print(f"  ✅ Saved: ATAC_normalized.h5ad")

# # ── Full verification ────────────────────────────────────────
# print("\n" + "=" * 60)
# print("PUBLICATION CHECKLIST")
# print("=" * 60)

# print(f"\n  Cells      : {adata_atac.n_obs:,}")
# print(f"  Peaks      : {adata_atac.n_vars:,}")
# print(f"  Layers     : {list(adata_atac.layers.keys())}")
# print(f"  Embeddings : {list(adata_atac.obsm.keys())}")

# print("\n  Cell balance:")
# for sname in ["h1_Pre_R1","h2_Post_R1","h3_Pre_R2","h4_Post_R2"]:
#     n = (adata_atac.obs["sample"] == sname).sum()
#     d = adata_atac.obs.loc[adata_atac.obs["sample"]==sname,"donor"].iloc[0]
#     s = adata_atac.obs.loc[adata_atac.obs["sample"]==sname,"status"].iloc[0]
#     print(f"    {sname:15s}  R{d[-1]} {s:4s}  {n:,} cells")

# X_raw    = adata_atac.layers["counts"]
# sparsity = 100*(1 - X_raw.nnz/(X_raw.shape[0]*X_raw.shape[1]))
# n_hvp    = int(adata_atac.var["highly_variable"].sum())

# print(f"\n  Sparsity    : {sparsity:.1f}%  (>95% = ✅ normal for ATAC)")
# print(f"  HVP         : {n_hvp:,} selected for LSI")
# print(f"  Norm        : TF-IDF → log1p  ✅")
# print(f"  LSI         : 50 components (use 2–30 in MOFA+)  ✅")
# print(f"  QC thresh   : TSS≥4, Frags 1k–50k, all samples  ✅")
# print(f"  Cell balance: ~10k per sample  ✅")
# print(f"  Reproducible: random.seed(42) for downsampling  ✅")

# print("\n" + "=" * 60)
# print("✅ ATAC pipeline complete — publication ready")
# print("=" * 60)
# print("""
#   NEXT PIPELINE: MuData + MOFA+
#   Files needed:
#     📄 BCG_annotated.h5ad           (RNA — from RNA pipeline)
#     📄 ATAC_normalized.h5ad         (ATAC — just saved above)
#     📁 New_BCG_ATAC_output/final/
# """)

# RESUME CELL — Run after any session crash
# Determines where you left off and reloads the right checkpoint.
# Run this instead of starting from Cell 3 after a crash.

import snapatac2 as snap
import anndata as ad
import scipy.sparse as sp
import scanpy as sc
import pandas as pd
import numpy as np
from pathlib import Path
import os

# Paths
FRAG_DIR   = Path("/content/drive/MyDrive/BCG_RAW/extracted")
QC_DIR     = Path("/content/drive/MyDrive/New_BCG_ATAC_output/1_qc")
PEAKS_DIR  = Path("/content/drive/MyDrive/New_BCG_ATAC_output/2_peaks")
MATRIX_DIR = Path("/content/drive/MyDrive/New_BCG_ATAC_output/4_matrices")
FINAL_DIR  = Path("/content/drive/MyDrive/New_BCG_ATAC_output/final")

SAMPLES = {
    "h1_Pre_R1" : {"file": "GSM8945136_Sample_BCG_h1_atac_fragments.tsv.gz",
                   "status": "Pre",  "donor": "R1", "gsm": "GSM8945136"},
    "h2_Post_R1": {"file": "GSM8945137_Sample_BCG_h2_atac_fragments.tsv.gz",
                   "status": "Post", "donor": "R1", "gsm": "GSM8945137"},
    "h3_Pre_R2" : {"file": "GSM8945138_Sample_BCG_h3_atac_fragments.tsv.gz",
                   "status": "Pre",  "donor": "R2", "gsm": "GSM8945138"},
    "h4_Post_R2": {"file": "GSM8945139_Sample_BCG_h4_atac_fragments.tsv.gz",
                   "status": "Post", "donor": "R2", "gsm": "GSM8945139"},
}

TSS_MIN, FRAG_MIN, FRAG_MAX, MAX_CELLS, SEED = 4, 1000, 50000, 10000, 42

# ── Check what's on Drive and resume from latest checkpoint ───
norm_path = FINAL_DIR / "ATAC_normalized.h5ad"
raw_path  = FINAL_DIR / "ATAC_combined_raw.h5ad"
npz_ok    = all((MATRIX_DIR / f"{s}_X.npz").exists() for s in SAMPLES)
peaks_ok  = all((PEAKS_DIR  / f"{s}_peaks.narrowPeak").exists() for s in SAMPLES)
tiles_ok  = all((QC_DIR     / f"{s}_tiles.h5ad").exists() for s in SAMPLES)
bc_ok     = all((QC_DIR     / f"{s}_barcodes.txt").exists() for s in SAMPLES)

print("Drive checkpoint status:")
print(f"  Tile files     : {'✅' if tiles_ok else '❌'}")
print(f"  Barcode files  : {'✅' if bc_ok else '❌'}")
print(f"  Peak files     : {'✅' if peaks_ok else '❌'}")
print(f"  Matrix .npz    : {'✅' if npz_ok else '❌'}")
print(f"  Combined h5ad  : {'✅' if raw_path.exists() else '❌'}")
print(f"  Normalized h5ad: {'✅' if norm_path.exists() else '❌'}")

if norm_path.exists():
    print("\n→ Loading ATAC_normalized.h5ad — resume from Cell 16 verification")
    adata_atac = sc.read_h5ad(str(norm_path))
    print(f"  ✅ {adata_atac.n_obs:,} cells × {adata_atac.n_vars:,} peaks loaded")

elif raw_path.exists() and npz_ok:
    print("\n→ Loading combined raw — resume from Cell 12 (TF-IDF)")
    adata_atac = sc.read_h5ad(str(raw_path))
    peak_matrices = {}
    for sname in SAMPLES:
        X      = sp.load_npz(str(MATRIX_DIR / f"{sname}_X.npz"))
        obs_df = pd.read_csv(str(MATRIX_DIR / f"{sname}_obs.csv"), index_col=0)
        var_df = pd.read_csv(str(MATRIX_DIR / f"{sname}_var.csv"), index_col=0)
        peak_matrices[sname] = ad.AnnData(X=X, obs=obs_df, var=var_df)
    print(f"  ✅ {adata_atac.n_obs:,} cells loaded — run Cell 12")

elif npz_ok:
    print("\n→ Matrices exist — resume from Cell 11 (combine)")
    peak_matrices = {}
    for sname in SAMPLES:
        X      = sp.load_npz(str(MATRIX_DIR / f"{sname}_X.npz"))
        obs_df = pd.read_csv(str(MATRIX_DIR / f"{sname}_obs.csv"), index_col=0)
        var_df = pd.read_csv(str(MATRIX_DIR / f"{sname}_var.csv"), index_col=0)
        for col in obs_df.columns:
            obs_df[col] = obs_df[col].astype(str).astype(object)
        peak_matrices[sname] = ad.AnnData(X=X, obs=obs_df, var=var_df)
        print(f"  ✅ {sname}: {peak_matrices[sname].n_obs:,} cells")
    print("  Run Cell 11 to combine")

elif peaks_ok and tiles_ok and bc_ok:
    print("\n→ Peaks + tiles exist — resume from Cell 10 (peak matrices)")
    import random
    adatas_raw = {}
    adatas_filtered = {}
    for sname, meta in SAMPLES.items():
        h5 = str(QC_DIR / f"{sname}_tiles.h5ad")
        a  = snap.read(h5)
        if "tsse" not in a.obs.columns:
            snap.metrics.tsse(a, gene_anno=snap.genome.hg38)
        adatas_raw[sname] = a
        snap.pp.filter_cells(a, min_counts=FRAG_MIN, max_counts=FRAG_MAX, min_tsse=TSS_MIN)
        if a.n_obs > MAX_CELLS:
            random.seed(SEED)
            keep = sorted(random.sample(range(a.n_obs), MAX_CELLS))
            a = a[keep].copy()
        adatas_filtered[sname] = a
        print(f"  ✅ {sname}: {a.n_obs:,} cells ready")
    print("  Run Cell 10")

elif tiles_ok:
    print("\n→ Tile files exist — resume from Cell 4 (TSS)")
    adatas_raw = {}
    for sname, meta in SAMPLES.items():
        a = snap.read(str(QC_DIR / f"{sname}_tiles.h5ad"))
        a.obs["status"] = [meta["status"]] * a.n_obs
        a.obs["donor"]  = [meta["donor"]]  * a.n_obs
        a.obs["gsm"]    = [meta["gsm"]]    * a.n_obs
        adatas_raw[sname] = a
        print(f"  ✅ {sname}: {a.n_obs:,} cells")
    print("  Run Cell 4")

else:
    print("\n→ No checkpoints found — run from Cell 3")

"""#BARCODE MATCHING RNA+ATAC and Mudata"""

import scanpy as sc
rna = sc.read_h5ad("/content/drive/MyDrive/BCG_annotated_final.h5ad")
print("orig_barcode first 5:")
print(rna.obs["orig_barcode"].head().tolist())
print("\nsample values:")
print(rna.obs["sample"].unique().tolist())

# DIAGNOSTIC — Run this and share ALL output before we proceed



rna  = sc.read_h5ad("/content/drive/MyDrive/BCG_annotated_final.h5ad")
atac = sc.read_h5ad("/content/drive/MyDrive/New_BCG_ATAC_output/final/ATAC_analysis_ready.h5ad")

print("=" * 60)
print("RNA OBJECT")
print("=" * 60)
print(f"  Shape          : {rna.n_obs:,} cells × {rna.n_vars:,} genes")
print(f"  obs_names[0:3] : {rna.obs_names[:3].tolist()}")
print(f"  obs columns    : {list(rna.obs.columns)}")
print(f"\n  sample values  : {rna.obs['sample'].unique().tolist()}")
print(f"  status values  : {rna.obs['status'].unique().tolist()}")
print(f"\n  orig_barcode[0:3]: {rna.obs['orig_barcode'].head(3).tolist()}")

# Check donor column
if 'donor' in rna.obs.columns:
    print(f"  donor values   : {rna.obs['donor'].unique().tolist()}")
else:
    print("  donor column   : ❌ NOT PRESENT in RNA")

# Check cell_type
if 'cell_type' in rna.obs.columns:
    print(f"  cell_types     : {rna.obs['cell_type'].unique().tolist()}")

print("\n" + "=" * 60)
print("ATAC OBJECT")
print("=" * 60)
print(f"  Shape          : {atac.n_obs:,} cells × {atac.n_vars:,} peaks")
print(f"  obs_names[0:3] : {atac.obs_names[:3].tolist()}")
print(f"  obs columns    : {list(atac.obs.columns)}")
print(f"\n  sample values  : {atac.obs['sample'].unique().tolist()}")
print(f"  status values  : {atac.obs['status'].unique().tolist()}")
print(f"  donor values   : {atac.obs['donor'].unique().tolist()}")

print("\n" + "=" * 60)
print("BARCODE FORMAT ANALYSIS")
print("=" * 60)

# RNA: show obs_names vs orig_barcode side by side
print("\nRNA — obs_names vs orig_barcode (first 5):")
for i in range(min(5, rna.n_obs)):
    print(f"  obs_name    : {rna.obs_names[i]}")
    print(f"  orig_barcode: {rna.obs['orig_barcode'].iloc[i]}")
    print(f"  sample      : {rna.obs['sample'].iloc[i]}")
    print()

# ATAC: show obs_names vs sample
print("ATAC — obs_names vs sample (first 5):")
for i in range(min(5, atac.n_obs)):
    print(f"  obs_name: {atac.obs_names[i]}")
    print(f"  sample  : {atac.obs['sample'].iloc[i]}")
    print()

# Check if any RNA and ATAC barcodes accidentally already match
rna_set  = set(rna.obs_names[:1000])
atac_set = set(atac.obs_names[:1000])
overlap  = rna_set & atac_set
print(f"Direct obs_names overlap (first 1000 each): {len(overlap)}")
if overlap:
    print(f"  Example match: {list(overlap)[:2]}")

# STEP 7+8 — Barcode Matching
# Verified against actual barcode formats

import scanpy as sc
import anndata as ad
import muon as mu
import numpy as np
import pandas as pd
from pathlib import Path

FINAL_DIR = Path("/content/drive/MyDrive/New_BCG_ATAC_output/final")

# ── Load objects ──────────────────────────────────────────────
print("Loading objects...")
rna  = sc.read_h5ad("/content/drive/MyDrive/BCG_annotated_final.h5ad")
atac = sc.read_h5ad(str(FINAL_DIR / "ATAC_analysis_ready.h5ad"))
print(f"  RNA  : {rna.n_obs:,} cells × {rna.n_vars:,} genes")
print(f"  ATAC : {atac.n_obs:,} cells × {atac.n_vars:,} peaks")

# ── Sample mapping ────────────────────────────────────────────
# ATAC sample key → RNA sample name
ATAC_TO_RNA = {
    "h1_Pre_R1" : "Sample_BCG_h1",
    "h2_Post_R1": "Sample_BCG_h2",
    "h3_Pre_R2" : "Sample_BCG_h3",
    "h4_Post_R2": "Sample_BCG_h4",
}

# RNA sample name → donor (derived — RNA has no donor column)
RNA_TO_DONOR = {
    "Sample_BCG_h1": "R1",
    "Sample_BCG_h2": "R1",
    "Sample_BCG_h3": "R2",
    "Sample_BCG_h4": "R2",
}

# RNA sample name → status
RNA_TO_STATUS = {
    "Sample_BCG_h1": "Pre",
    "Sample_BCG_h2": "Post",
    "Sample_BCG_h3": "Pre",
    "Sample_BCG_h4": "Post",
}

# ── STEP 7A: Extract raw barcodes from RNA ────────────────────
# RNA obs_name: "Sample_BCG_h3#CAAGACAAGTCTTGAA-1"
# raw barcode = part after "#"
print("\nExtracting RNA raw barcodes...")
rna_raw_bc = pd.Series(
    [obs.split("#")[1] for obs in rna.obs_names],
    index=rna.obs_names
)
# Match key = raw_barcode__sample  (using __ as separator)
rna_match = rna_raw_bc + "__" + rna.obs["sample"].astype(str)
rna.obs["match_key"] = rna_match.values
print(f"  Example: {rna.obs_names[0]} → key: {rna.obs['match_key'].iloc[0]}")

# ── STEP 7B: Extract raw barcodes from ATAC ───────────────────
# ATAC obs_name: "h1_Pre_R1_AAACAGCCAAACCTAT-1-h1_Pre_R1"
# raw barcode = strip prefix "h1_Pre_R1_" and suffix "-h1_Pre_R1"
print("\nExtracting ATAC raw barcodes...")
atac_match_keys = []
atac_raw_barcodes = []

for obs_name in atac.obs_names:
    # Get sample key from obs (e.g. "h1_Pre_R1")
    # Find which sample this barcode belongs to
    skey = None
    for s in ATAC_TO_RNA:
        if obs_name.startswith(s + "_"):
            skey = s
            break

    if skey is None:
        # Fallback: use sample column
        idx = atac.obs_names.get_loc(obs_name)
        skey = atac.obs["sample"].iloc[idx]

    # Strip prefix: "h1_Pre_R1_AAACAGCCAAACCTAT-1-h1_Pre_R1"
    #                          → "AAACAGCCAAACCTAT-1-h1_Pre_R1"
    prefix = skey + "_"
    rest   = obs_name[len(prefix):]    # "AAACAGCCAAACCTAT-1-h1_Pre_R1"

    # Strip suffix: "-h1_Pre_R1"
    suffix = "-" + skey
    if rest.endswith(suffix):
        raw_bc = rest[: -len(suffix)]  # "AAACAGCCAAACCTAT-1"
    else:
        raw_bc = rest

    # Build match key using RNA sample name
    rna_sample = ATAC_TO_RNA[skey]
    match_key  = raw_bc + "__" + rna_sample

    atac_match_keys.append(match_key)
    atac_raw_barcodes.append(raw_bc)

atac.obs["match_key"] = atac_match_keys
atac.obs["raw_barcode"] = atac_raw_barcodes
print(f"  Example: {atac.obs_names[0]}")
print(f"  → raw_bc : {atac_raw_barcodes[0]}")
print(f"  → key    : {atac_match_keys[0]}")

# ── STEP 7C: Find intersection ────────────────────────────────
print("\nFinding barcode intersection...")
rna_keys  = set(rna.obs["match_key"])
atac_keys = set(atac.obs["match_key"])
common    = rna_keys & atac_keys

pct_rna  = 100 * len(common) / len(rna_keys)
pct_atac = 100 * len(common) / len(atac_keys)

print(f"  RNA  keys : {len(rna_keys):,}")
print(f"  ATAC keys : {len(atac_keys):,}")
print(f"  Common    : {len(common):,}")
print(f"  % of RNA  : {pct_rna:.1f}%")
print(f"  % of ATAC : {pct_atac:.1f}%")

if pct_rna < 30:
    # Debug: show sample-level breakdown
    print("\n  ❌ Low match rate — debugging per sample:")
    for skey, rna_s in ATAC_TO_RNA.items():
        rna_n  = (rna.obs["sample"]  == rna_s).sum()
        atac_n = (atac.obs["sample"] == skey).sum()
        # keys for this sample
        rk = {k for k in rna_keys  if k.endswith("__" + rna_s)}
        ak = {k for k in atac_keys if k.endswith("__" + rna_s)}
        ov = rk & ak
        print(f"  {skey} ↔ {rna_s}: RNA={rna_n} ATAC={atac_n} match={len(ov)}")
    raise ValueError("Match rate <30% — see per-sample debug above")

print(f"\n  ✅ Match rate acceptable — proceeding")

# ── STEP 7D: Subset to matched cells ─────────────────────────
print("\nSubsetting to matched cells...")
common_sorted = sorted(common)

# Set match_key as index for both
rna_idx  = rna.obs["match_key"].values
atac_idx = atac.obs["match_key"].values

rna.obs_names  = pd.Index(rna_idx)
atac.obs_names = pd.Index(atac_idx)

rna_matched  = rna[common_sorted].copy()
atac_matched = atac[common_sorted].copy()

# Verify order is identical (critical for MuData)
assert list(rna_matched.obs_names) == list(atac_matched.obs_names), \
    "❌ Cell order mismatch"
print(f"  ✅ Cell order verified — identical in both modalities")

# ── Add donor column to RNA (derived from sample) ─────────────
# RNA has no donor column — we add it now for MOFA+ grouping
rna_matched.obs["donor"] = (
    rna_matched.obs["sample"].map(RNA_TO_DONOR).values
)
rna_matched.obs["status"] = (
    rna_matched.obs["sample"].map(RNA_TO_STATUS).values
)

print(f"\n  Matched RNA  : {rna_matched.n_obs:,} × {rna_matched.n_vars:,}")
print(f"  Matched ATAC : {atac_matched.n_obs:,} × {atac_matched.n_vars:,}")

print("\n  Per-sample breakdown:")
for skey, rna_s in ATAC_TO_RNA.items():
    n = (rna_matched.obs["sample"] == rna_s).sum()
    print(f"    {rna_s} ({skey}): {n:,} cells")

# ── STEP 8: Build MuData ──────────────────────────────────────
print("\nBuilding MuData...")

# Add cell_type to ATAC obs (transferred from RNA)
atac_matched.obs["cell_type"] = rna_matched.obs["cell_type"].values

mdata = mu.MuData({
    "rna" : rna_matched,
    "atac": atac_matched,
})

# Add global obs metadata (accessible at mdata level)
mdata.obs["sample"]    = rna_matched.obs["sample"].values
mdata.obs["status"]    = rna_matched.obs["status"].values
mdata.obs["donor"]     = rna_matched.obs["donor"].values
mdata.obs["cell_type"] = rna_matched.obs["cell_type"].values

print(f"  ✅ MuData built:")
print(f"     Cells      : {mdata.n_obs:,}")
print(f"     RNA genes  : {mdata['rna'].n_vars:,}")
print(f"     ATAC peaks : {mdata['atac'].n_vars:,}")
print(f"     obs cols   : {list(mdata.obs.columns)}")

# ── Save ──────────────────────────────────────────────────────
mdata_path = str(FINAL_DIR / "BCG_multiome.h5mu")
mdata.write(mdata_path)
print(f"\n  ✅ Saved: BCG_multiome.h5mu")

# ── Final verification ────────────────────────────────────────
print("\n" + "=" * 60)
print("STEP 7+8 COMPLETE")
print("=" * 60)
print(f"""
  Matched cells : {mdata.n_obs:,}
  RNA genes     : {mdata['rna'].n_vars:,}
  ATAC peaks    : {mdata['atac'].n_vars:,}

  RNA  obs cols : {[c for c in rna_matched.obs.columns if c in
                    ['sample','status','donor','cell_type']]}
  ATAC obs cols : {[c for c in atac_matched.obs.columns if c in
                    ['sample','status','donor','cell_type']]}

  Donor breakdown:
    R1 cells: {(mdata.obs['donor']=='R1').sum():,}
    R2 cells: {(mdata.obs['donor']=='R2').sum():,}

  Status breakdown:
    Pre cells : {(mdata.obs['status']=='Pre').sum():,}
    Post cells: {(mdata.obs['status']=='Post').sum():,}

  Saved: {mdata_path}
  NEXT : MOFA+ factor analysis
""")

"""checking"""

# Verify where the unmatched ATAC cells come from
print("Unmatched ATAC cells per sample:")
matched_keys = set(common_sorted)
for skey, rna_s in ATAC_TO_RNA.items():
    total_atac   = (atac.obs["sample"] == skey).sum()
    matched_atac = sum(1 for k in matched_keys if k.endswith("__" + rna_s))
    print(f"  {skey}: {total_atac:,} total → {matched_atac:,} matched "
          f"({100*matched_atac/total_atac:.1f}%)")

# Check RNA cell counts per sample before and after matching
print("RNA cells per sample:")
for s in ["Sample_BCG_h1","Sample_BCG_h2","Sample_BCG_h3","Sample_BCG_h4"]:
    n_rna      = (rna.obs["sample"] == s).sum()
    n_matched  = (rna_matched.obs["sample"] == s).sum()
    print(f"  {s}: {n_rna:,} RNA cells → {n_matched:,} matched")

# DIAGNOSTIC — Why did h1 lose so many RNA cells?
import scanpy as sc
import numpy as np

rna_full = sc.read_h5ad("/content/drive/MyDrive/BCG_annotated_final.h5ad")

print("RNA QC metrics per sample:")
print(f"{'Sample':<20} {'Cells':>8} {'Med genes':>12} "
      f"{'Med counts':>12} {'Med MT%':>10}")
print("-" * 65)

for s in ["Sample_BCG_h1","Sample_BCG_h2",
          "Sample_BCG_h3","Sample_BCG_h4"]:
    mask = rna_full.obs["sample"] == s
    sub  = rna_full.obs[mask]
    n    = mask.sum()

    med_genes  = np.median(sub["n_genes_by_counts"])   if "n_genes_by_counts"  in sub else "N/A"
    med_counts = np.median(sub["total_counts"])         if "total_counts"       in sub else "N/A"
    med_mt     = np.median(sub["pct_counts_mt"])        if "pct_counts_mt"      in sub else "N/A"

    print(f"  {s:<18} {n:>8,} {med_genes:>12.0f} "
          f"{med_counts:>12.0f} {med_mt:>10.2f}%")

# Also check doublet scores for h1
print("\nDoublet scores per sample:")
for s in ["Sample_BCG_h1","Sample_BCG_h2",
          "Sample_BCG_h3","Sample_BCG_h4"]:
    mask = rna_full.obs["sample"] == s
    sub  = rna_full.obs[mask]
    if "predicted_doublet" in sub.columns:
        n_doublet = sub["predicted_doublet"].sum()
        pct       = 100 * n_doublet / len(sub)
        print(f"  {s}: {n_doublet:,} doublets removed ({pct:.1f}%)")
    if "doublet_score" in sub.columns:
        print(f"    median doublet score: {np.median(sub['doublet_score']):.3f}")