# -*- coding: utf-8 -*-
"""GEO: GSE295308 - CD34+ subtype annotation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KJGA65G-lnCmTglyor_RLeSHGQWAhOVx
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
import sys
if 'google.colab' in sys.modules:
#   %pip install scanpy anndata pandas numpy matplotlib

import scanpy as sc
import anndata as ad
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

file_path = "/content/drive/MyDrive/BCG_preprocessed_for_R.h5ad"

adata = ad.read_h5ad(file_path)

print(adata)

adata.obs.head()

adata.obs["leiden"].value_counts()

sc.pl.umap(adata, color=["leiden", "status", "sample"])

import scanpy as sc

sc.tl.rank_genes_groups(
    adata,
    groupby="leiden",
    method="wilcoxon",
    n_genes=50
)

sc.pl.rank_genes_groups(adata, n_genes=20, sharey=False, save='rank_genes_groups.png')

markers = sc.get.rank_genes_groups_df(adata, group=None)
markers

for cl in sorted(adata.obs["leiden"].unique()):

    print("\n====================")
    print("Cluster:", cl)

    display(
        markers[markers["group"] == str(cl)][
            ["names","logfoldchanges","pvals_adj"]
        ].head(15)
    )

# The 'HSPC_subtype' column is not found in adata.obs or adata.var.
# You need to define this column in adata.obs before plotting.
# For demonstration, we'll temporarily assign 'leiden' values to 'HSPC_subtype'.
# You will need to replace this with your actual HSPC subtype annotations.
adata.obs['HSPC_subtype'] = adata.obs['leiden'].astype('category')
sc.pl.umap(adata, color=["HSPC_subtype"])

sc.pl.umap(
    adata,
    color=[
        "CD34", "GATA2", "HLF", "MEIS1", "MSI2", "SOX4", "FLT3", "PROM1",
        "NKG7", "FCGR3A", "IL7R", "CD74", "JCHAIN"
    ],
    ncols=4,
    save='umap_marker_genes.png'
)

marker_dict = {
    "HSPC": ["CD34", "GATA2", "HLF", "MEIS1", "MSI2", "FLT3", "PROM1", "SOX4"],
    "T_cell": ["IL7R", "LEF1", "BCL11B", "LTB"],
    "NK": ["NKG7", "GNLY", "PRF1", "KLRD1"],
    "Monocyte": ["VCAN", "FCN1", "FCGR3A", "CTSS", "MS4A7", "LYZ"],
    "B_cell": ["BANK1", "CD79A", "MS4A1", "CD74", "HLA-DRA"],
    "Plasma": ["JCHAIN", "MZB1", "IGHA1", "TNFRSF17"],
    "pDC_DC": ["TCF4", "BCL11A", "HLA-DRA", "CD74"],
    "Cycling": ["MKI67", "STMN1", "TOP2A"]
}

sc.pl.dotplot(
    adata,
    marker_dict,
    groupby="leiden",
    standard_scale="var",
    save='dotplot.png'
)

cluster_to_broadtype = {
    "0": "T_cell_IL7R",
    "1": "Monocyte_VCAN_FCN1",
    "2": "NK_CCL5_NKG7",
    "3": "Cytotoxic_NK_FCGR3A",
    "4": "Monocyte_FCGR3A",
    "5": "B_cell",
    "6": "HSPC_like",
    "7": "Memory_T_GZMK",
    "8": "DC_APC_like",
    "9": "pDC_like",
    "10": "Plasma_cell",
    "11": "Cycling"
}

adata.obs["broad_celltype"] = adata.obs["leiden"].astype(str).map(cluster_to_broadtype)
sc.pl.umap(adata, color=["broad_celltype", "status"], wspace=0.4, save='umap_broad_celltype.png')

hspc_clusters = ["6"]

adata_hspc = adata[adata.obs["leiden"].astype(str).isin(hspc_clusters)].copy()

print(adata_hspc)

sc.pp.highly_variable_genes(adata_hspc, n_top_genes=2000)
sc.pp.scale(adata_hspc)

sc.tl.pca(adata_hspc)

sc.pp.neighbors(adata_hspc, n_neighbors=15)
sc.tl.umap(adata_hspc)

sc.tl.leiden(adata_hspc, resolution=0.3)

sc.pl.umap(adata_hspc, color=["status"])

adata.write_h5ad(
"/content/drive/MyDrive/BCG_preprocessed_annotated.h5ad",
compression="gzip"
)