# -*- coding: utf-8 -*-
"""GSE176178 Validation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LWloVyu2-WEY4ic1vf_coad54pzUi0L-
"""

# ============================================================
# GSE176178 - BCG Bladder Cancer Genomic Data
# Load from GEO and Save to Google Drive
# ============================================================

# Step 1: Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Step 2: Install required libraries
!pip install GEOparse -q

# Step 3: Import libraries
import GEOparse
import pandas as pd
import os
import gzip
import shutil
import urllib.request

# Step 4: Define save path
SAVE_DIR = '/content/drive/MyDrive/GSE176178_validation'
os.makedirs(SAVE_DIR, exist_ok=True)
print(f"Save directory: {SAVE_DIR}")

# ============================================================
# Step 5: Load the GEO Series using GEOparse
# ============================================================
print("\nDownloading GSE176178 from GEO...")
gse = GEOparse.get_GEO(geo="GSE176178", destdir=SAVE_DIR, silent=False)

# ============================================================
# Step 6: Extract and Save Metadata
# ============================================================
print("\nExtracting metadata...")

# Series-level metadata
series_meta = {
    'title': gse.metadata.get('title', [''])[0],
    'summary': gse.metadata.get('summary', [''])[0],
    'overall_design': gse.metadata.get('overall_design', [''])[0],
    'submission_date': gse.metadata.get('submission_date', [''])[0],
    'organism': gse.metadata.get('sample_organism', ['Homo sapiens'])[0],
}
series_meta_df = pd.DataFrame([series_meta])
series_meta_df.to_csv(f"{SAVE_DIR}/series_metadata.csv", index=False)
print("Series metadata saved.")

# Sample-level metadata
sample_records = []
for gsm_name, gsm in gse.gsms.items():
    record = {
        'gsm_accession': gsm_name,
        'title': gsm.metadata.get('title', [''])[0],
        'source': gsm.metadata.get('source_name_ch1', [''])[0],
        'organism': gsm.metadata.get('organism_ch1', [''])[0],
        'characteristics': str(gsm.metadata.get('characteristics_ch1', '')),
        'description': gsm.metadata.get('description', [''])[0],
    }
    sample_records.append(record)

sample_meta_df = pd.DataFrame(sample_records)
sample_meta_df.to_csv(f"{SAVE_DIR}/sample_metadata.csv", index=False)
print(f"Sample metadata saved — {len(sample_records)} samples.")

# ============================================================
# Step 7: Download the Processed Count Matrix
# (GSE176178_RNA.featurecounts.txt.gz)
# ============================================================
print("\nDownloading processed RNA featureCounts matrix...")

count_url = "https://ftp.ncbi.nlm.nih.gov/geo/series/GSE176nnn/GSE176178/suppl/GSE176178_RNA.featurecounts.txt.gz"
gz_path   = f"{SAVE_DIR}/GSE176178_RNA.featurecounts.txt.gz"
txt_path  = f"{SAVE_DIR}/GSE176178_RNA.featurecounts.txt"

# Download
urllib.request.urlretrieve(count_url, gz_path)
print("Download complete.")

# Decompress
with gzip.open(gz_path, 'rb') as f_in, open(txt_path, 'wb') as f_out:
    shutil.copyfileobj(f_in, f_out)
print("Decompressed successfully.")

# ============================================================
# Step 8: Load Count Matrix into DataFrame
# ============================================================
print("\nLoading count matrix...")
counts_df = pd.read_csv(txt_path, sep='\t', comment='#')
print(f"Count matrix shape: {counts_df.shape}")
print(counts_df.head())

# Save a clean copy as CSV for easy downstream use
counts_csv_path = f"{SAVE_DIR}/GSE176178_featurecounts.csv"
counts_df.to_csv(counts_csv_path, index=False)
print(f"\nCount matrix saved as CSV: {counts_csv_path}")

# ============================================================
# Step 9: Summary
# ============================================================
print("\n" + "="*55)
print("All files saved to:", SAVE_DIR)
print("="*55)
for f in os.listdir(SAVE_DIR):
    fpath = os.path.join(SAVE_DIR, f)
    size_mb = os.path.getsize(fpath) / 1e6
    print(f"  {f:50s}  {size_mb:.2f} MB")

# Check what's inside the sample metadata
import pandas as pd

sample_meta_df = pd.read_csv('/content/drive/MyDrive/GSE176178_validation/sample_metadata.csv')

# See all columns
print(sample_meta_df.columns.tolist())
print("\n")

# See full characteristics field for all samples
pd.set_option('display.max_colwidth', None)
print(sample_meta_df[['gsm_accession', 'title', 'source', 'characteristics']].to_string())

# Dig into raw GSM metadata fields
for gsm_name, gsm in gse.gsms.items():
    print(f"\n{gsm_name}:")
    for key, val in gsm.metadata.items():
        print(f"  {key}: {val}")
    break  # Remove 'break' to see all 40 samples

import pandas as pd
import ast

# Load metadata
sample_meta_df = pd.read_csv('/content/drive/MyDrive/GSE176178_validation/sample_metadata.csv')

# Parse characteristics column
def parse_characteristics(char_str):
    char_list = ast.literal_eval(char_str)
    result = {}
    for item in char_list:
        key, val = item.split(': ', 1)
        result[key.strip()] = val.strip()
    return result

# Apply parsing
parsed = sample_meta_df['characteristics'].apply(parse_characteristics)
parsed_df = pd.DataFrame(parsed.tolist())

# Combine with accession and title
meta_clean = pd.concat([
    sample_meta_df[['gsm_accession', 'title']],
    parsed_df
], axis=1)

# Rename for clarity
meta_clean.rename(columns={
    'title': 'sample_id',
    'bcg response': 'bcg_response',
    'age': 'age',
    'gender': 'gender'
}, inplace=True)

meta_clean['age'] = meta_clean['age'].astype(int)

print(meta_clean)
print("\nValue counts:")
print(meta_clean['bcg_response'].value_counts())

# Save
meta_clean.to_csv('/content/drive/MyDrive/GSE176178_validation/sample_metadata_clean.csv', index=False)
print("\nSaved: sample_metadata_clean.csv")

import pandas as pd

# Load count matrix
counts_df = pd.read_csv('/content/drive/MyDrive/GSE176178_validation/GSE176178_featurecounts.csv')

# Check Geneid column
print("Total genes:", len(counts_df))
print("\nFirst 10 gene names:")
print(counts_df['Geneid'].head(10).tolist())

# Check if any look like Ensembl IDs (ENSG...)
ensembl_check = counts_df['Geneid'].str.startswith('ENSG').sum()
print(f"\nEnsembl IDs present: {ensembl_check}")
print(f"Gene symbols present: {len(counts_df) - ensembl_check}")

# Check annotation columns vs sample columns
annotation_cols = ['Geneid', 'Chr', 'Start', 'End', 'Strand', 'Length']
sample_cols = [c for c in counts_df.columns if c not in annotation_cols]

print(f"\nAnnotation columns: {annotation_cols}")
print(f"\nSample columns ({len(sample_cols)}): {sample_cols}")

import pandas as pd
import ast

# ============================================================
# Load files
# ============================================================
counts_df = pd.read_csv('/content/drive/MyDrive/GSE176178_validation/GSE176178_featurecounts.csv')
meta_clean = pd.read_csv('/content/drive/MyDrive/GSE176178_validation/sample_metadata_clean.csv')

# ============================================================
# Step 1: Clean count matrix — keep only Geneid + sample cols
# ============================================================
annotation_cols = ['Chr', 'Start', 'End', 'Strand', 'Length']
counts_clean = counts_df.drop(columns=annotation_cols)

# Set Geneid as index
counts_clean = counts_clean.set_index('Geneid')

print("Count matrix shape:", counts_clean.shape)
print(counts_clean.head())

# ============================================================
# Step 2: Transpose — rows = samples, columns = genes
# ============================================================
counts_T = counts_clean.T  # Now: 40 samples x 59412 genes
counts_T.index.name = 'sample_id'
counts_T = counts_T.reset_index()

print("\nTransposed shape:", counts_T.shape)

# ============================================================
# Step 3: Merge with metadata (sample_id + bcg_response)
# ============================================================
meta_subset = meta_clean[['sample_id', 'gsm_accession', 'bcg_response', 'age', 'gender']]

final_df = meta_subset.merge(counts_T, on='sample_id', how='inner')

# Reorder: metadata first, then genes
meta_cols = ['sample_id', 'gsm_accession', 'bcg_response', 'age', 'gender']
gene_cols  = [c for c in final_df.columns if c not in meta_cols]

final_df = final_df[meta_cols + gene_cols]

print("\nFinal matrix shape:", final_df.shape)
print(final_df.iloc[:5, :8])  # Preview first 8 columns

# ============================================================
# Step 4: Save full matrix
# ============================================================
out_path = '/content/drive/MyDrive/GSE176178_validation/GSE176178_patient_gene_matrix.csv'
final_df.to_csv(out_path, index=False)
print(f"\nSaved full matrix: {out_path}")

import pandas as pd
import numpy as np
from scipy import stats
from sklearn.metrics import roc_auc_score

# ============================================================
# Step 1: Load your gene signature
# ============================================================
sig_file = pd.read_csv('/content/drive/MyDrive/BCG_MOFA_output/hspc_analysis/BCG_signature_core_50.csv')
my_genes = sig_file['gene'].tolist()
print(f"Total signature genes: {len(my_genes)}")
print(f"First 10: {my_genes[:10]}")

# ============================================================
# Step 2: Load the patient-gene matrix
# ============================================================
final_df = pd.read_csv('/content/drive/MyDrive/GSE176178_validation/GSE176178_patient_gene_matrix.csv')
print(f"\nPatient matrix shape: {final_df.shape}")

# ============================================================
# Step 3: Check gene overlap
# ============================================================
meta_cols  = ['sample_id', 'gsm_accession', 'bcg_response', 'age', 'gender']
gene_cols  = [c for c in final_df.columns if c not in meta_cols]

available_genes = [g for g in my_genes if g in gene_cols]
missing_genes   = [g for g in my_genes if g not in gene_cols]

print(f"\nSignature genes found in dataset : {len(available_genes)}")
print(f"Signature genes NOT found        : {len(missing_genes)}")
print(f"Missing genes: {missing_genes}")

# ============================================================
# Step 4: Create signature matrix
# ============================================================
sig_matrix = final_df[meta_cols + available_genes].copy()

# Split by response group
responders     = sig_matrix[sig_matrix['bcg_response'] == 'Yes']
non_responders = sig_matrix[sig_matrix['bcg_response'] == 'No']

print(f"\nResponders    : {len(responders)}")
print(f"Non-Responders: {len(non_responders)}")

# ============================================================
# Step 5: Per-gene stats — p-value + AUC
# ============================================================
# Binary label: Yes=1, No=0
y_true = (sig_matrix['bcg_response'] == 'Yes').astype(int).values

results = []

for gene in available_genes:
    r_vals  = responders[gene].values
    nr_vals = non_responders[gene].values
    all_vals = sig_matrix[gene].values

    # Mann-Whitney U test
    try:
        stat, pval = stats.mannwhitneyu(r_vals, nr_vals, alternative='two-sided')
    except Exception:
        pval = np.nan

    # AUC
    try:
        auc = roc_auc_score(y_true, all_vals)
        # Flip if AUC < 0.5 (gene suppressed in responders)
        if auc < 0.5:
            auc_flipped = 1 - auc
            direction   = 'down_in_responders'
        else:
            auc_flipped = auc
            direction   = 'up_in_responders'
    except Exception:
        auc_flipped = np.nan
        direction   = 'NA'

    results.append({
        'gene'           : gene,
        'mean_responder' : round(r_vals.mean(), 3),
        'mean_nonresp'   : round(nr_vals.mean(), 3),
        'log2FC'         : round(np.log2((r_vals.mean() + 1) / (nr_vals.mean() + 1)), 3),
        'p_value'        : round(pval, 5),
        'AUC'            : round(auc_flipped, 3),
        'direction'      : direction,
    })

results_df = pd.DataFrame(results)

# Add FDR correction (Benjamini-Hochberg)
from statsmodels.stats.multitest import multipletests
reject, pvals_corr, _, _ = multipletests(results_df['p_value'].fillna(1), method='fdr_bh')
results_df['p_adj_BH'] = pvals_corr.round(5)
results_df['significant'] = reject

# Sort by AUC descending
results_df = results_df.sort_values('AUC', ascending=False).reset_index(drop=True)

# ============================================================
# Step 6: Display results
# ============================================================
print("\n===== TOP GENES BY AUC =====")
print(results_df.head(20).to_string(index=False))

print("\n===== SIGNIFICANT GENES (p_adj < 0.05) =====")
sig_genes = results_df[results_df['p_adj_BH'] < 0.05]
print(sig_genes.to_string(index=False))

print(f"\nTotal significant genes: {len(sig_genes)}")

# ============================================================
# Step 7: Save results
# ============================================================
out_path = '/content/drive/MyDrive/GSE176178_validation/BCG_signature_validation_results.csv'
results_df.to_csv(out_path, index=False)
print(f"\nSaved: {out_path}")

# ============================================================
# Step 8: Overall signature score per patient (mean expression)
# ============================================================
sig_matrix = sig_matrix.copy()
sig_matrix['signature_score'] = sig_matrix[available_genes].mean(axis=1)

# AUC of signature score
score_auc = roc_auc_score(y_true, sig_matrix['signature_score'].values)
print(f"\n===== OVERALL SIGNATURE SCORE AUC =====")
print(f"AUC of mean signature score: {score_auc:.4f}")

# Mean score per group
print("\nMean signature score by group:")
print(sig_matrix.groupby('bcg_response')['signature_score'].mean().round(3))

# Mann-Whitney on signature score
r_scores  = sig_matrix[sig_matrix['bcg_response'] == 'Yes']['signature_score'].values
nr_scores = sig_matrix[sig_matrix['bcg_response'] == 'No']['signature_score'].values
_, score_pval = stats.mannwhitneyu(r_scores, nr_scores, alternative='two-sided')
print(f"Signature score p-value     : {score_pval:.5f}")

# Save score matrix
score_path = '/content/drive/MyDrive/GSE176178_validation/GSE176178_signature_scores.csv'
sig_matrix[meta_cols + ['signature_score']].to_csv(score_path, index=False)
print(f"Saved: {score_path}")

import pandas as pd
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
import seaborn as sns

# ============================================================
# Load files
# ============================================================
final_df  = pd.read_csv('/content/drive/MyDrive/GSE176178_validation/GSE176178_patient_gene_matrix.csv')
results   = pd.read_csv('/content/drive/MyDrive/GSE176178_validation/BCG_signature_validation_results.csv')
scores_df = pd.read_csv('/content/drive/MyDrive/GSE176178_validation/GSE176178_signature_scores.csv')

meta_cols = ['sample_id', 'gsm_accession', 'bcg_response', 'age', 'gender']

# ============================================================
# 1. Check XIST vs Gender
# ============================================================
print("=== XIST expression by Gender ===")
print(final_df.groupby('gender')['XIST'].mean().round(1))

print("\n=== Gender distribution by BCG response ===")
print(pd.crosstab(final_df['bcg_response'], final_df['gender']))

# ============================================================
# 2. Rerun AUC excluding XIST — use only "up" direction genes
# ============================================================
sig_file = pd.read_csv('/content/drive/MyDrive/BCG_MOFA_output/hspc_analysis/BCG_signature_standard_100.csv')
my_genes = sig_file['gene'].tolist()

# Merge results with direction info
up_genes = results[results['direction'] == 'up_in_responders']['gene'].tolist()
down_genes = results[results['direction'] == 'down_in_responders']['gene'].tolist()

print(f"\nGenes UP in responders   : {len(up_genes)} → {up_genes}")
print(f"Genes DOWN in responders : {len(down_genes)}")

# ============================================================
# 3. Signature score WITHOUT XIST
# ============================================================
from sklearn.metrics import roc_auc_score

y_true = (final_df['bcg_response'] == 'Yes').astype(int).values

genes_no_xist = [g for g in my_genes if g != 'XIST']
final_df['score_no_xist'] = final_df[genes_no_xist].mean(axis=1)

auc_no_xist = roc_auc_score(y_true, final_df['score_no_xist'])
_, pval_no_xist = stats.mannwhitneyu(
    final_df[final_df['bcg_response']=='Yes']['score_no_xist'],
    final_df[final_df['bcg_response']=='No']['score_no_xist'],
    alternative='two-sided'
)
print(f"\n=== Signature Score WITHOUT XIST ===")
print(f"AUC    : {auc_no_xist:.4f}")
print(f"p-value: {pval_no_xist:.5f}")

# ============================================================
# 4. Gender-stratified analysis
# ============================================================
print("\n=== Gender-stratified signature AUC ===")
for gender in ['Male', 'Female']:
    sub = final_df[final_df['gender'] == gender].copy()
    if sub['bcg_response'].nunique() < 2:
        print(f"{gender}: only one response group — skipping")
        continue
    y_sub = (sub['bcg_response'] == 'Yes').astype(int).values
    score_sub = sub[genes_no_xist].mean(axis=1).values
    try:
        auc_sub = roc_auc_score(y_sub, score_sub)
        _, p_sub = stats.mannwhitneyu(
            sub[sub['bcg_response']=='Yes'][genes_no_xist].mean(axis=1),
            sub[sub['bcg_response']=='No'][genes_no_xist].mean(axis=1),
            alternative='two-sided'
        )
        print(f"  {gender}: AUC={auc_sub:.3f}, p={p_sub:.4f}, n={len(sub)}")
    except:
        print(f"  {gender}: Could not compute AUC")

# ============================================================
# 5. Plot: Signature score boxplot by response
# ============================================================
fig, axes = plt.subplots(1, 3, figsize=(15, 5))

# A) Full signature score
scores_df_merged = scores_df.merge(final_df[['sample_id','gender']], on='sample_id')
sns.boxplot(data=scores_df_merged, x='bcg_response', y='signature_score',
            palette={'Yes':'steelblue','No':'salmon'}, ax=axes[0])
axes[0].set_title(f'Full Signature Score\nAUC=0.616, p=0.218')
axes[0].set_xlabel('BCG Response')
axes[0].set_ylabel('Mean Signature Score')

# B) Score without XIST
final_df_plot = final_df[['sample_id','bcg_response','gender','score_no_xist']].copy()
sns.boxplot(data=final_df_plot, x='bcg_response', y='score_no_xist',
            palette={'Yes':'steelblue','No':'salmon'}, ax=axes[1])
axes[1].set_title(f'Signature Score (excl. XIST)\nAUC={auc_no_xist:.3f}, p={pval_no_xist:.4f}')
axes[1].set_xlabel('BCG Response')
axes[1].set_ylabel('Mean Score (no XIST)')

# C) XIST expression by response + gender
final_df['label'] = final_df['bcg_response'] + '_' + final_df['gender']
sns.boxplot(data=final_df, x='bcg_response', y='XIST',
            hue='gender', palette='Set2', ax=axes[2])
axes[2].set_title('XIST Expression\n(Response × Gender)')
axes[2].set_xlabel('BCG Response')
axes[2].set_ylabel('XIST counts')

plt.tight_layout()
plt.savefig('/content/drive/MyDrive/GSE176178_validation/BCG_signature_validation_plots.png',
            dpi=150, bbox_inches='tight')
plt.show()
print("\nPlot saved!")

# ============================================================
# 6. Top genes summary table
# ============================================================
print("\n=== Full results ranked by AUC ===")
print(results[['gene','mean_responder','mean_nonresp',
               'log2FC','p_value','AUC','direction','p_adj_BH']].to_string(index=False))