# -*- coding: utf-8 -*-
"""GSE199471 - Recurrence Validation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DxIpRcbdxdeFUjP39FOYpeTbpPvzEVud
"""

from google.colab import drive
drive.mount('/content/drive')

import os

DATASET_ID = "GSE199471"
DRIVE_BASE = "/content/drive/MyDrive"
SAVE_DIR = os.path.join(DRIVE_BASE, DATASET_ID)

os.makedirs(SAVE_DIR, exist_ok=True)

print("Save folder created / confirmed:")
print(SAVE_DIR)

import os
import urllib.request

DATASET_ID = "GSE199471"
SAVE_DIR = f"/content/drive/MyDrive/{DATASET_ID}"

file_url = "https://ftp.ncbi.nlm.nih.gov/geo/series/GSE199nnn/GSE199471/suppl/GSE199471_CPM_table.txt.gz"
file_name = "GSE199471_CPM_table.txt.gz"
save_path = os.path.join(SAVE_DIR, file_name)

urllib.request.urlretrieve(file_url, save_path)

print("Downloaded successfully:")
print(save_path)
print("File size (MB):", round(os.path.getsize(save_path) / (1024*1024), 2))

import os

for f in os.listdir(SAVE_DIR):
    print(f)

import gzip
import shutil
import os

gz_path = os.path.join(SAVE_DIR, "GSE199471_CPM_table.txt.gz")
txt_path = os.path.join(SAVE_DIR, "GSE199471_CPM_table.txt")

with gzip.open(gz_path, "rb") as f_in:
    with open(txt_path, "wb") as f_out:
        shutil.copyfileobj(f_in, f_out)

print("Unzipped file saved at:")
print(txt_path)
print("File size (MB):", round(os.path.getsize(txt_path) / (1024*1024), 2))

import pandas as pd
import os

txt_path = os.path.join(SAVE_DIR, "GSE199471_CPM_table.txt")

df = pd.read_csv(txt_path, sep="\t")
print(df.shape)
df

import gzip
import shutil
import os

gz_path = os.path.join(SAVE_DIR, "GSE199471_series_matrix.txt.gz")
txt_path = os.path.join(SAVE_DIR, "GSE199471_series_matrix.txt")

with gzip.open(gz_path, "rb") as f_in:
    with open(txt_path, "wb") as f_out:
        shutil.copyfileobj(f_in, f_out)

print("Unzipped file saved at:")
print(txt_path)
print("File size (MB):", round(os.path.getsize(txt_path) / (1024*1024), 2))

txt_path = "/content/drive/MyDrive/GSE199471/GSE199471_series_matrix.txt"

with open(txt_path) as f:
    for i in range(100):
        print(f.readline())

import pandas as pd
import os

# Path
SAVE_DIR = "/content/drive/MyDrive/GSE199471"

# Load your expression file
expr_path = os.path.join(SAVE_DIR, "GSE199471_CPM_table.txt")  # adjust if needed
expr_df = pd.read_csv(expr_path, sep="\t")

# -------------------------------
# Selected samples (IMPORTANT)
# -------------------------------
selected_samples = [
    # baseline
    "D378R011","D378R016","D378R017","D378R019","D378R023",
    "D378R027","D378R029","D378R032","D378R015","D378R022",
    "D378R025","D378R030","D378R033","D378R079",

    # recurrence
    "D378R060","D378R062","D378R073","D378R074","D378R078",
    "D378R086","D378R088","D378R080","D378R081","D378R082","D378R083"
]

# -------------------------------
# Keep gene info + selected samples
# -------------------------------
gene_cols = ["Gene", "Description", "Gene_biotype", "Gene_position"]

filtered_df = expr_df[gene_cols + selected_samples]

# -------------------------------
# Save new CSV
# -------------------------------
output_path = os.path.join(SAVE_DIR, "GSE199471_filtered_expression.csv")
filtered_df.to_csv(output_path, index=False)

print("✅ Filtered expression file saved at:")
print(output_path)

print("\nShape of filtered data:")
filtered_df.shape

import pandas as pd
import os

SAVE_DIR = "/content/drive/MyDrive/GSE199471"

# Load expression data
expr_path = os.path.join(SAVE_DIR, "GSE199471_CPM_table.txt")
expr_df = pd.read_csv(expr_path, sep="\t")

# -------------------------------
# Sample groups
# -------------------------------
baseline_samples = [
    "D378R011","D378R016","D378R017","D378R019","D378R023",
    "D378R027","D378R029","D378R032","D378R015","D378R022",
    "D378R025","D378R030","D378R033","D378R079"
]

recurrence_samples = [
    "D378R060","D378R062","D378R073","D378R074","D378R078",
    "D378R086","D378R088","D378R080","D378R081","D378R082","D378R083"
]

selected_samples = baseline_samples + recurrence_samples

# -------------------------------
# Keep only selected columns
# -------------------------------
gene_cols = ["Gene", "Description", "Gene_biotype", "Gene_position"]
filtered_df = expr_df[gene_cols + selected_samples]

# -------------------------------
# Create group row
# -------------------------------
group_labels = [""] * len(gene_cols) + \
               ["baseline"] * len(baseline_samples) + \
               ["recurrence"] * len(recurrence_samples)

group_row = pd.DataFrame([group_labels], columns=filtered_df.columns)

# -------------------------------
# Combine group row + data
# -------------------------------
final_df = pd.concat([group_row, filtered_df], ignore_index=True)

# -------------------------------
# Save CSV
# -------------------------------
output_path = os.path.join(SAVE_DIR, "GSE199471_filtered_expression_with_groups.csv")
final_df.to_csv(output_path, index=False)

print("✅ Saved file with group labels at:")
print(output_path)

import os
import pandas as pd
import numpy as np
from scipy.stats import mannwhitneyu
from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import StandardScaler

# ============================================================
# PATHS
# ============================================================
SAVE_DIR = "/content/drive/MyDrive/GSE199471"
SIG_DIR  = "/content/drive/MyDrive/BCG_Top200_Signature"

expr_path = os.path.join(SAVE_DIR, "GSE199471_filtered_expression.csv")
sig_path  = os.path.join(SIG_DIR, "primary_signature_top200_genes_only.csv")

# output files
score_csv   = os.path.join(SAVE_DIR, "GSE199471_signature_scores.csv")
summary_csv = os.path.join(SAVE_DIR, "GSE199471_signature_summary.csv")

# ============================================================
# LOAD DATA
# ============================================================
expr_df = pd.read_csv(expr_path)
sig_df  = pd.read_csv(sig_path)

print("Expression shape:", expr_df.shape)
print("Signature shape :", sig_df.shape)

# ============================================================
# GET SIGNATURE GENE LIST
# ============================================================
# Try to detect the gene column automatically
possible_gene_cols = ["gene", "Gene", "genes", "GENE"]
gene_col_sig = None
for c in possible_gene_cols:
    if c in sig_df.columns:
        gene_col_sig = c
        break

if gene_col_sig is None:
    # if only one column exists, use that
    if sig_df.shape[1] == 1:
        gene_col_sig = sig_df.columns[0]
    else:
        raise ValueError(f"Could not detect gene column in signature file. Columns: {sig_df.columns.tolist()}")

signature_genes = (
    sig_df[gene_col_sig]
    .astype(str)
    .str.strip()
    .str.upper()
    .dropna()
    .unique()
    .tolist()
)

print("Top200 signature genes loaded:", len(signature_genes))

# ============================================================
# IDENTIFY SAMPLE COLUMNS
# ============================================================
meta_cols = ["Gene", "Description", "Gene_biotype", "Gene_position", "CumulativeLengthExon"]
meta_cols_present = [c for c in meta_cols if c in expr_df.columns]

sample_cols = [c for c in expr_df.columns if c not in meta_cols_present]

print("Metadata columns:", meta_cols_present)
print("Sample columns:", len(sample_cols))

# ============================================================
# DEFINE GROUPS
# ============================================================
baseline_samples = [
    "D378R011","D378R016","D378R017","D378R019","D378R023",
    "D378R027","D378R029","D378R032","D378R015","D378R022",
    "D378R025","D378R030","D378R033","D378R079"
]

recurrence_samples = [
    "D378R060","D378R062","D378R073","D378R074","D378R078",
    "D378R086","D378R088","D378R080","D378R081","D378R082","D378R083"
]

# keep only samples that actually exist in the expression matrix
baseline_samples = [s for s in baseline_samples if s in sample_cols]
recurrence_samples = [s for s in recurrence_samples if s in sample_cols]

selected_samples = baseline_samples + recurrence_samples

print("Baseline samples found  :", len(baseline_samples))
print("Recurrence samples found:", len(recurrence_samples))

if len(selected_samples) == 0:
    raise ValueError("No selected samples were found in the expression matrix.")

# ============================================================
# MATCH GENES
# ============================================================
if "Gene" not in expr_df.columns:
    raise ValueError("Expression file must contain a 'Gene' column.")

expr_df["Gene_clean"] = expr_df["Gene"].astype(str).str.strip().str.upper()

matched_df = expr_df[expr_df["Gene_clean"].isin(signature_genes)].copy()

print("Matched signature genes in dataset:", matched_df.shape[0])

if matched_df.shape[0] == 0:
    raise ValueError("No signature genes matched the expression dataset.")

# ============================================================
# CALCULATE SIGNATURE SCORE
# Method: z-score each gene across samples, then average per sample
# This makes genes comparable before averaging
# ============================================================
expr_mat = matched_df[selected_samples].copy()

# force numeric
expr_mat = expr_mat.apply(pd.to_numeric, errors="coerce")

# z-score by gene (row-wise across samples)
row_means = expr_mat.mean(axis=1)
row_stds  = expr_mat.std(axis=1).replace(0, np.nan)

z_mat = expr_mat.sub(row_means, axis=0).div(row_stds, axis=0)
z_mat = z_mat.fillna(0)

# average across genes for each sample
signature_scores = z_mat.mean(axis=0)

score_df = pd.DataFrame({
    "Sample_ID": selected_samples,
    "Signature_Score": [signature_scores[s] for s in selected_samples],
    "Group": ["baseline"] * len(baseline_samples) + ["recurrence"] * len(recurrence_samples)
})

# ============================================================
# STATISTICS
# ============================================================
baseline_scores = score_df.loc[score_df["Group"] == "baseline", "Signature_Score"].values
recurrence_scores = score_df.loc[score_df["Group"] == "recurrence", "Signature_Score"].values

# one-sided hypothesis:
# baseline > recurrence  (equivalent to recurrence lower than baseline)
u_stat, p_two_sided = mannwhitneyu(baseline_scores, recurrence_scores, alternative="two-sided")
u_stat_one, p_one_sided = mannwhitneyu(baseline_scores, recurrence_scores, alternative="greater")

# ROC AUC
# label recurrence as 1
y_true = (score_df["Group"] == "recurrence").astype(int).values

# If higher score means more protective, then lower score should indicate recurrence.
# So for ROC toward recurrence, use negative score.
auc = roc_auc_score(y_true, -score_df["Signature_Score"].values)

summary = pd.DataFrame([{
    "n_signature_genes_input": len(signature_genes),
    "n_signature_genes_matched": int(matched_df.shape[0]),
    "n_baseline": int(len(baseline_scores)),
    "n_recurrence": int(len(recurrence_scores)),
    "mean_baseline_score": float(np.mean(baseline_scores)),
    "mean_recurrence_score": float(np.mean(recurrence_scores)),
    "median_baseline_score": float(np.median(baseline_scores)),
    "median_recurrence_score": float(np.median(recurrence_scores)),
    "mannwhitney_u_two_sided": float(u_stat),
    "p_value_two_sided": float(p_two_sided),
    "p_value_one_sided_baseline_gt_recurrence": float(p_one_sided),
    "roc_auc_recurrence_using_negative_score": float(auc)
}])

# ============================================================
# SAVE
# ============================================================
score_df.to_csv(score_csv, index=False)
summary.to_csv(summary_csv, index=False)

print("\n✅ Saved score file:")
print(score_csv)

print("\n✅ Saved summary file:")
print(summary_csv)

print("\n=== SUMMARY ===")
print(summary.T)

print("\nTop rows of score table:")
print(score_df.head())