# -*- coding: utf-8 -*-
"""GEO_GSE295308_scRNA_(BCG)-Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16p-qiv7I4O5zZWjYUN_gH5DIOx6eUqNL
"""

# Install libraries
# BiocManager::install(c("DESeq2", "WGCNA", "ComplexHeatmap"))
# devtools::install_github("smorabit/hdWGCNA")
# devtools::install_github("mojaveazure/seurat-disk")

library(Seurat)
library(SeuratDisk)
library(hdWGCNA)
library(DESeq2)
library(tidyverse)
library(magrittr)

googledrive::drive_deauth()


googledrive::drive_auth(scopes = "https://www.googleapis.com/auth/drive")


file_id <- "1frlreB-qYNWg3d94W5h2U5mDsWJpBEXL"
googledrive::drive_download(
  googledrive::as_id(file_id),
  path = "BCG_preprocessed_for_R.h5ad",
  overwrite = TRUE
)

install.packages("vctrs", repos = "https://cran.rstudio.com/")

# 2. Install the Bioconductor manager
if (!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager")

# 3. Install the biological dependencies needed for WGCNA/hdWGCNA
# This fixes the "non-zero exit status" error
BiocManager::install(c("preprocessCore", "impute", "SummarizedExperiment", "GenomicRanges", "GeneOverlap", "UCell"))

# Install the main tools
remotes::install_github("mojaveazure/seurat-disk")
remotes::install_github("smorabit/hdWGCNA")

# Verify they load!
library(Seurat)
library(SeuratDisk)
library(hdWGCNA)

library(Seurat)
library(Matrix)

# 1. Load the pieces
counts <- readMM("counts.mtx")
meta <- read.csv("metadata.csv", row.names = 1)
genes <- read.csv("genes.csv")[[1]]
harmony <- read.csv("harmony.csv", row.names = 1)

# 2. Assemble the Seurat Object
rownames(counts) <- genes
colnames(counts) <- rownames(meta)
seurat_obj <- CreateSeuratObject(counts = counts, meta.data = meta)

# 3. Inject the Harmony reduction
harmony_mat <- as.matrix(harmony)
rownames(harmony_mat) <- colnames(seurat_obj)
seurat_obj[["pca_harmony"]] <- CreateDimReducObject(
  embeddings = harmony_mat,
  key = "harmony_",
  assay = "RNA"
)

# 4. Success check
print(seurat_obj)

"""hdWGCNA"""