# -*- coding: utf-8 -*-
"""TCGA_BLCA_Validation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L3mk1pRrhM-bYojyoha1eH6pCq7mS6GZ
"""



"""#Loading TCGA-BLCA"""

# -*- coding: utf-8 -*-
"""
TCGA-BLCA Extract + Verify
===========================
Upload blca_tcga_pan_can_atlas_2018.tar.gz to Drive first,
then run this cell to extract and verify the needed files.
"""

# ─────────────────────────────────────────────────────────────
# CELL 0 — Mount Drive
# ─────────────────────────────────────────────────────────────
from google.colab import drive
drive.mount('/content/drive', force_remount=False)

import os, tarfile, shutil, warnings
import pandas as pd
import numpy as np
warnings.filterwarnings("ignore")

SAVE_DIR  = "/content/drive/MyDrive/tcga_blca_validation"
TAR_PATH  = os.path.join(SAVE_DIR, "blca_tcga_pan_can_atlas_2018.tar.gz")
EXTRACT_DIR = os.path.join(SAVE_DIR, "extracted")

os.makedirs(SAVE_DIR, exist_ok=True)
os.makedirs(EXTRACT_DIR, exist_ok=True)

# ─────────────────────────────────────────────────────────────
# CELL 1 — Confirm tar.gz is present
# ─────────────────────────────────────────────────────────────
print("=" * 65)
print("Step 1: Checking tar.gz")
print("=" * 65)

if not os.path.exists(TAR_PATH):
    raise FileNotFoundError(
        f"\n❌ File not found: {TAR_PATH}"
        f"\n   Upload blca_tcga_pan_can_atlas_2018.tar.gz to:"
        f"\n   MyDrive/tcga_blca_validation/ and re-run."
    )

size_mb = os.path.getsize(TAR_PATH) / (1024 ** 2)
print(f"  ✅ Found: blca_tcga_pan_can_atlas_2018.tar.gz  ({size_mb:.1f} MB)")


# ─────────────────────────────────────────────────────────────
# CELL 2 — List contents of tar.gz (without extracting yet)
# ─────────────────────────────────────────────────────────────
print("\n" + "=" * 65)
print("Step 2: Contents of archive")
print("=" * 65)

with tarfile.open(TAR_PATH, "r:gz") as tar:
    members = tar.getnames()

print(f"  Total files in archive: {len(members)}")
print("\n  All files:")
for m in sorted(members):
    print(f"    {m}")


# ─────────────────────────────────────────────────────────────
# CELL 3 — Extract only the 3 files we need
# ─────────────────────────────────────────────────────────────
print("\n" + "=" * 65)
print("Step 3: Extracting needed files")
print("=" * 65)

# Files we need (just the basename — archive may have a subfolder prefix)
NEEDED = [
    "data_mrna_seq_v2_rsem.txt",
    "data_clinical_patient.txt",
    "data_clinical_sample.txt",
]

with tarfile.open(TAR_PATH, "r:gz") as tar:
    all_names = tar.getnames()

    for needed in NEEDED:
        # Find the matching member (handles subfolder like blca_.../data_mrna...)
        match = next((m for m in all_names if m.endswith(needed)), None)

        if match is None:
            print(f"  ⚠️  {needed} — NOT FOUND in archive")
            print(f"       Available files: {[os.path.basename(m) for m in all_names[:10]]}")
            continue

        dest_path = os.path.join(SAVE_DIR, needed)

        # Skip if already extracted and large enough
        if os.path.exists(dest_path) and os.path.getsize(dest_path) > 50_000:
            kb = os.path.getsize(dest_path) / 1024
            print(f"  ⏭  {needed:<45} already exists ({kb:,.0f} KB)")
            continue

        # Extract this specific member
        member = tar.getmember(match)
        member.name = needed          # flatten path — strip any subfolder prefix
        tar.extract(member, path=SAVE_DIR)

        kb = os.path.getsize(dest_path) / 1024
        print(f"  ✅  {needed:<45} {kb:>10,.1f} KB")


# ─────────────────────────────────────────────────────────────
# CELL 4 — Verify and preview extracted files
# ─────────────────────────────────────────────────────────────
print("\n" + "=" * 65)
print("Step 4: Verify file sizes")
print("=" * 65)

MIN_SIZES = {
    "data_mrna_seq_v2_rsem.txt":  10_000,   # ~50 MB
    "data_clinical_patient.txt":      50,   # ~100 KB
    "data_clinical_sample.txt":       50,   # ~150 KB
}

all_ok = True
for fn, min_kb in MIN_SIZES.items():
    fp = os.path.join(SAVE_DIR, fn)
    if not os.path.exists(fp):
        print(f"  ❌  {fn:<45}  MISSING")
        all_ok = False
    else:
        kb = os.path.getsize(fp) / 1024
        ok = kb >= min_kb
        mark = "✅" if ok else "❌ TOO SMALL — re-extract"
        print(f"  {mark}  {fn:<45}  {kb:>10,.1f} KB")
        if not ok:
            all_ok = False

if not all_ok:
    raise SystemExit("\n❌ Some files are missing or too small. Check errors above.")


# ─────────────────────────────────────────────────────────────
# CELL 5 — Quick data preview
# ─────────────────────────────────────────────────────────────
print("\n" + "=" * 65)
print("Step 5: Data preview")
print("=" * 65)

# ── Expression matrix ─────────────────────────────────────────
print("\n── Expression matrix ───────────────────────────────────────")
expr = pd.read_csv(
    os.path.join(SAVE_DIR, "data_mrna_seq_v2_rsem.txt"),
    sep="\t", index_col=0, low_memory=False
)
if "Entrez_Gene_Id" in expr.columns:
    expr = expr.drop(columns=["Entrez_Gene_Id"])

print(f"  Shape     : {expr.shape[0]:,} genes × {expr.shape[1]:,} patients")
print(f"  Genes     : {list(expr.index[:5])} ...")
print(f"  Patients  : {list(expr.columns[:4])} ...")
vals = expr.iloc[:200, :50].values.astype(float)
print(f"  Values    : min={np.nanmin(vals):.2f}  max={np.nanmax(vals):.2f}  mean={np.nanmean(vals):.2f}")
print(f"  ✅ Already log2 normalized — ready for ssGSEA directly")

# ── Clinical data ─────────────────────────────────────────────
print("\n── Clinical data ───────────────────────────────────────────")
clin = pd.read_csv(
    os.path.join(SAVE_DIR, "data_clinical_patient.txt"),
    sep="\t", comment="#", low_memory=False
)
print(f"  Shape     : {clin.shape[0]:,} patients × {clin.shape[1]:,} columns")
print(f"\n  Columns available:")
for col in clin.columns:
    n = clin[col].notna().sum()
    print(f"    {col:<50}  {n:>3} non-null")

# ── Check survival columns exist ──────────────────────────────
print("\n── Survival column check ───────────────────────────────────")
KEY_COLS = ["OS_STATUS", "OS_MONTHS", "DFS_STATUS", "DFS_MONTHS",
            "AGE", "AJCC_PATHOLOGIC_TUMOR_STAGE", "SEX"]
for col in KEY_COLS:
    found = col in clin.columns
    n     = clin[col].notna().sum() if found else 0
    print(f"  {'✅' if found else '❌'}  {col:<45}  {n if found else 'NOT FOUND'}")

# ─────────────────────────────────────────────────────────────
# DONE
# ─────────────────────────────────────────────────────────────
print("\n" + "=" * 65)
print("✅ Extraction complete. Files saved to:")
print(f"   {SAVE_DIR}")
print("""
Next step:
  → Run the ssGSEA scoring script with your 100-gene signature
    to generate per-patient BCG-HSPC enrichment scores.
""")

# -*- coding: utf-8 -*-
"""
BCG-HSPC Signature Validation — TCGA-BLCA
==========================================
Step 1 : Load 100-gene BCG signature from Drive
Step 2 : Clean + log2-transform expression matrix
Step 3 : ssGSEA scoring (gseapy)
Step 4 : Kaplan-Meier survival (OS + PFS)
Step 5 : Cox proportional hazards regression
Step 6 : Save all results + figures to Drive

Signature source : MyDrive/BCG_MOFA_output/hspc_analysis/BCG_signature_up_standard_100*
Data source      : MyDrive/tcga_blca_validation/
"""

# ─────────────────────────────────────────────────────────────
# CELL 0 — Mount Drive + install packages
# ─────────────────────────────────────────────────────────────
from google.colab import drive
drive.mount('/content/drive', force_remount=False)

import subprocess, os

def run(cmd, label=""):
    print(f"  → {label}")
    r = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    out = (r.stdout + r.stderr).strip()
    if out: print(out[-300:])

print("Installing packages...")
run("pip install -q gseapy",                        "gseapy (ssGSEA)")
run("pip install -q lifelines",                     "lifelines (KM + Cox)")
run("pip install -q matplotlib seaborn pandas numpy scipy", "plotting + stats")
run("pip install -q statsmodels",                   "statsmodels")
print("✅ Done\n")

# ─────────────────────────────────────────────────────────────
# CELL 1 — Paths
# ─────────────────────────────────────────────────────────────
import os
from pathlib import Path

DATA_DIR = Path("/content/drive/MyDrive/tcga_blca_validation")
SIG_DIR  = Path("/content/drive/MyDrive/BCG_MOFA_output/hspc_analysis")
OUT_DIR  = DATA_DIR / "results"
OUT_DIR.mkdir(parents=True, exist_ok=True)

print("Paths:")
print(f"  Data dir : {DATA_DIR}")
print(f"  Sig  dir : {SIG_DIR}")
print(f"  Out  dir : {OUT_DIR}")

# CELL 2 — Load BCG signature genes from Drive
# ─────────────────────────────────────────────────────────────
import pandas as pd
import numpy as np
import glob

print("\n" + "="*65)
print("STEP 1: Loading BCG-HSPC 100-gene signature")
print("="*65)

# Search for the signature file — handles .csv, .txt, .tsv variants
sig_patterns = [
    str(SIG_DIR / "BCG_signature_up_standard_100*"),
    str(SIG_DIR / "*up_standard_100*"),
    str(SIG_DIR / "*signature*up*100*"),
    str(SIG_DIR / "*BCG_signature_genes*"),
]

sig_file = None
for pattern in sig_patterns:
    matches = glob.glob(pattern)
    if matches:
        sig_file = matches[0]
        break

if sig_file is None:
    # List what IS in the hspc_analysis folder to help debug
    print("❌ Signature file not found. Files in hspc_analysis/:")
    for f in sorted(SIG_DIR.glob("*")):
        print(f"   {f.name}")
    raise FileNotFoundError(
        "Signature file not found. "
        "Check the filename in MyDrive/BCG_MOFA_output/hspc_analysis/"
    )

print(f"  ✅ Found: {os.path.basename(sig_file)}")

# ── Load the gene list ────────────────────────────────────────
ext = Path(sig_file).suffix.lower()

if ext in [".csv", ".tsv", ".txt"]:
    # Try reading as CSV/TSV first
    try:
        sig_df = pd.read_csv(sig_file, sep=None, engine="python")
        print(f"  Columns in file: {list(sig_df.columns)}")

        # Find the gene name column — common names
        gene_col_candidates = [
            c for c in sig_df.columns
            if any(k in c.lower() for k in ["gene", "name", "symbol", "hugo"])
        ]
        if gene_col_candidates:
            gene_col = gene_col_candidates[0]
        else:
            gene_col = sig_df.columns[0]   # fallback: first column

        print(f"  Using column: '{gene_col}'")
        bcg_genes = sig_df[gene_col].dropna().astype(str).str.strip().tolist()

    except Exception:
        # Plain text file — one gene per line
        with open(sig_file) as f:
            bcg_genes = [
                line.strip() for line in f
                if line.strip() and not line.startswith("#")
            ]

# Remove any empty/numeric strings
bcg_genes = [g for g in bcg_genes if g and not g.isdigit()]

print(f"\n  Total genes loaded : {len(bcg_genes)}")
print(f"  First 10 genes     : {bcg_genes[:10]}")
print(f"  Last  10 genes     : {bcg_genes[-10:]}")

if len(bcg_genes) < 10:
    raise ValueError(f"Only {len(bcg_genes)} genes loaded — check the file format")

# ─────────────────────────────────────────────────────────────
# CELL 3 — Load + clean expression matrix
# ─────────────────────────────────────────────────────────────
print("\n" + "="*65)
print("STEP 2: Loading + cleaning expression matrix")
print("="*65)

expr_raw = pd.read_csv(
    DATA_DIR / "data_mrna_seq_v2_rsem.txt",
    sep="\t", index_col=0, low_memory=False
)

# Drop Entrez ID column if present
if "Entrez_Gene_Id" in expr_raw.columns:
    expr_raw = expr_raw.drop(columns=["Entrez_Gene_Id"])

print(f"  Raw shape : {expr_raw.shape[0]:,} genes × {expr_raw.shape[1]:,} patients")

# ── 2a. Drop rows with missing gene names ─────────────────────
expr_raw = expr_raw[expr_raw.index.notna()]
expr_raw = expr_raw[expr_raw.index.astype(str).str.strip() != ""]
expr_raw = expr_raw[expr_raw.index.astype(str) != "nan"]
expr_raw.index = expr_raw.index.astype(str).str.strip()
print(f"  After dropping NaN gene names : {expr_raw.shape[0]:,} genes")

# ── 2b. Handle duplicate gene names (keep highest mean expression) ──
expr_raw = expr_raw.astype(float)
expr_raw = expr_raw.groupby(expr_raw.index).mean()
print(f"  After deduplication           : {expr_raw.shape[0]:,} genes")

# ── 2c. Log2 transform ────────────────────────────────────────
# Values showed max ~39,000 → raw RSEM scale, needs log2(x+1)
vmax = expr_raw.values.max()
if vmax > 100:
    print(f"  Max value = {vmax:.1f} → applying log2(x+1) transform")
    expr_log2 = np.log2(expr_raw + 1)
else:
    print(f"  Max value = {vmax:.1f} → already log2-scale, no transform needed")
    expr_log2 = expr_raw

print(f"  After log2 transform: min={expr_log2.values.min():.2f}  "
      f"max={expr_log2.values.max():.2f}  "
      f"mean={expr_log2.values.mean():.2f}")

# ── 2d. Check signature gene overlap ─────────────────────────
sig_in_data  = [g for g in bcg_genes if g in expr_log2.index]
sig_missing  = [g for g in bcg_genes if g not in expr_log2.index]
pct_overlap  = 100 * len(sig_in_data) / len(bcg_genes)

print(f"\n  Signature genes found in matrix : {len(sig_in_data)}/{len(bcg_genes)} ({pct_overlap:.1f}%)")
if sig_missing:
    print(f"  Missing genes                   : {sig_missing[:20]}")
    if len(sig_missing) > 20:
        print(f"  ... and {len(sig_missing)-20} more")

if pct_overlap < 50:
    print("  ⚠️  Less than 50% overlap — check gene symbol format in signature file")
elif pct_overlap >= 80:
    print("  ✅ Good overlap — ssGSEA will be reliable")

# Save cleaned matrix
expr_log2.to_csv(OUT_DIR / "expr_log2_clean.csv.gz", compression="gzip")
print(f"\n  ✅ Clean log2 matrix saved → results/expr_log2_clean.csv.gz")

# ─────────────────────────────────────────────────────────────
# CELL 4 — ssGSEA scoring
# ─────────────────────────────────────────────────────────────
print("\n" + "="*65)
print("STEP 3: ssGSEA scoring")
print("="*65)

import gseapy as gp

# ssGSEA expects: gene_sets = dict of {name: [genes]}
gene_sets = {"BCG_HSPC_Signature": sig_in_data}

print(f"  Running ssGSEA on {expr_log2.shape[1]} patients × {len(sig_in_data)} signature genes...")
print(f"  (This takes ~2-5 minutes)")

ss = gp.ssgsea(
    data        = expr_log2,          # genes × samples
    gene_sets   = gene_sets,
    outdir      = None,               # don't write intermediate files
    sample_norm_method = "rank",      # standard for ssGSEA
    no_plot     = True,
    processes   = 4,
    seed        = 42,
)

# Extract scores — result is samples × gene_sets
scores_df = ss.res2d

# Pivot to get one row per patient, one column = BCG_HSPC_Signature score
if "Term" in scores_df.columns and "NES" in scores_df.columns:
    # gseapy ≥0.10 format
    scores_pivot = scores_df.pivot(index="Name", columns="Term", values="NES")
elif "es" in scores_df.columns.str.lower().tolist():
    scores_pivot = scores_df
else:
    # Fallback: transpose if needed
    scores_pivot = scores_df.T

scores_pivot.index.name = "SAMPLE_ID"
scores_pivot.columns.name = None

# Rename score column for clarity
if "BCG_HSPC_Signature" in scores_pivot.columns:
    scores_pivot = scores_pivot.rename(columns={"BCG_HSPC_Signature": "BCG_score"})
else:
    scores_pivot.columns = ["BCG_score"]

print(f"\n  ssGSEA complete!")
print(f"  Score shape : {scores_pivot.shape}")
print(f"  Score range : min={scores_pivot['BCG_score'].min():.4f}  "
      f"max={scores_pivot['BCG_score'].max():.4f}  "
      f"mean={scores_pivot['BCG_score'].mean():.4f}")

scores_pivot.to_csv(OUT_DIR / "bcg_ssgsea_scores.csv")
print(f"  ✅ Scores saved → results/bcg_ssgsea_scores.csv")

# ─────────────────────────────────────────────────────────────
# CELL 5 — Merge scores with clinical data
# ─────────────────────────────────────────────────────────────
print("\n" + "="*65)
print("STEP 4: Merging scores with clinical data")
print("="*65)

clin_raw = pd.read_csv(
    DATA_DIR / "data_clinical_patient.txt",
    sep="\t", comment="#", low_memory=False
)

# ── Parse OS and PFS status → binary ──────────────────────────
# cBioPortal format: "1:DECEASED" → 1,  "0:LIVING" → 0
def parse_status(col):
    return col.astype(str).str[0].astype(int)

clin = clin_raw.copy()
clin["OS_EVENT"]  = parse_status(clin["OS_STATUS"])
clin["OS_MONTHS"] = pd.to_numeric(clin["OS_MONTHS"], errors="coerce")
clin["PFS_EVENT"] = parse_status(clin["PFS_STATUS"])
clin["PFS_MONTHS"]= pd.to_numeric(clin["PFS_MONTHS"], errors="coerce")
clin["AGE"]       = pd.to_numeric(clin["AGE"], errors="coerce")

# Simplify stage: Stage I/II = early, Stage III/IV = late
def simplify_stage(s):
    s = str(s).upper()
    if any(x in s for x in ["IV", "III"]): return "Late"
    if any(x in s for x in ["I", "II"]):   return "Early"
    return np.nan

clin["STAGE_SIMPLE"] = clin["AJCC_PATHOLOGIC_TUMOR_STAGE"].apply(simplify_stage)

# ── Match sample IDs to patient IDs ───────────────────────────
# Expression sample: TCGA-2F-A9KO-01  →  patient: TCGA-2F-A9KO
scores_pivot["PATIENT_ID"] = scores_pivot.index.str[:12]

merged = scores_pivot.merge(
    clin[["PATIENT_ID","OS_EVENT","OS_MONTHS",
          "PFS_EVENT","PFS_MONTHS","AGE",
          "STAGE_SIMPLE","AJCC_PATHOLOGIC_TUMOR_STAGE",
          "SEX","PATH_T_STAGE"]],
    on="PATIENT_ID", how="inner"
)

print(f"  Patients after merge : {len(merged)}")
print(f"  OS events            : {merged['OS_EVENT'].sum()} deaths")
print(f"  PFS events           : {merged['PFS_EVENT'].sum()} progressions")
print(f"  BCG score range      : {merged['BCG_score'].min():.4f} – {merged['BCG_score'].max():.4f}")

# ── Stratify: HIGH vs LOW by median split ─────────────────────
median_score = merged["BCG_score"].median()
merged["BCG_GROUP"] = np.where(merged["BCG_score"] >= median_score, "High", "Low")

print(f"\n  Median BCG score     : {median_score:.4f}")
print(f"  BCG-High patients    : {(merged['BCG_GROUP']=='High').sum()}")
print(f"  BCG-Low  patients    : {(merged['BCG_GROUP']=='Low').sum()}")

merged.to_csv(OUT_DIR / "merged_scores_clinical.csv", index=False)
print(f"\n  ✅ Merged data saved → results/merged_scores_clinical.csv")

# ─────────────────────────────────────────────────────────────
# CELL 6 — Score distribution plot
# ─────────────────────────────────────────────────────────────
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import seaborn as sns

fig, axes = plt.subplots(1, 2, figsize=(12, 4))
fig.suptitle("BCG-HSPC Signature Score Distribution — TCGA-BLCA",
             fontsize=13, fontweight="bold")

# Histogram
axes[0].hist(merged["BCG_score"], bins=40, color="#4C72B0", edgecolor="white", alpha=0.85)
axes[0].axvline(median_score, color="red", linestyle="--", linewidth=1.5, label=f"Median = {median_score:.3f}")
axes[0].set_xlabel("ssGSEA BCG-HSPC Score", fontsize=11)
axes[0].set_ylabel("Number of patients", fontsize=11)
axes[0].set_title("Score distribution")
axes[0].legend()

# Boxplot High vs Low
sns.boxplot(data=merged, x="BCG_GROUP", y="BCG_score",
            palette={"High": "#E74C3C", "Low": "#3498DB"},
            order=["High","Low"], ax=axes[1], width=0.5)
axes[1].set_xlabel("BCG Signature Group", fontsize=11)
axes[1].set_ylabel("ssGSEA BCG-HSPC Score", fontsize=11)
axes[1].set_title("High vs Low stratification")

plt.tight_layout()
fig.savefig(OUT_DIR / "01_score_distribution.png", dpi=150, bbox_inches="tight")
plt.close()
print("✅ Saved → results/01_score_distribution.png")

# ─────────────────────────────────────────────────────────────
# CELL 7 — Kaplan-Meier: Overall Survival
# ─────────────────────────────────────────────────────────────
print("\n" + "="*65)
print("STEP 5a: Kaplan-Meier — Overall Survival (OS)")
print("="*65)

from lifelines import KaplanMeierFitter
from lifelines.statistics import logrank_test
from lifelines.plotting import add_at_risk_counts

fig, ax = plt.subplots(figsize=(8, 6))

kmf_high = KaplanMeierFitter(label="BCG-High")
kmf_low  = KaplanMeierFitter(label="BCG-Low")

high = merged[merged["BCG_GROUP"] == "High"].dropna(subset=["OS_MONTHS","OS_EVENT"])
low  = merged[merged["BCG_GROUP"] == "Low"].dropna(subset=["OS_MONTHS","OS_EVENT"])

kmf_high.fit(high["OS_MONTHS"], high["OS_EVENT"])
kmf_low.fit( low["OS_MONTHS"],  low["OS_EVENT"])

kmf_high.plot_survival_function(ax=ax, color="#E74C3C", linewidth=2.5, ci_show=True)
kmf_low.plot_survival_function( ax=ax, color="#3498DB", linewidth=2.5, ci_show=True)

# Log-rank test
lr_os = logrank_test(
    high["OS_MONTHS"], low["OS_MONTHS"],
    event_observed_A=high["OS_EVENT"],
    event_observed_B=low["OS_EVENT"]
)

# Median survival
med_high = kmf_high.median_survival_time_
med_low  = kmf_low.median_survival_time_

ax.set_xlabel("Time (months)", fontsize=12)
ax.set_ylabel("Overall Survival Probability", fontsize=12)
ax.set_title("BCG-HSPC Signature — Overall Survival\nTCGA-BLCA (n=407)", fontsize=12)
ax.set_ylim(0, 1.05)

# Annotate p-value
pval_text = f"Log-rank p = {lr_os.p_value:.4f}"
if lr_os.p_value < 0.001:
    pval_text = f"Log-rank p < 0.001"
ax.text(0.65, 0.85, pval_text, transform=ax.transAxes,
        fontsize=11, fontweight="bold",
        bbox=dict(boxstyle="round,pad=0.3", facecolor="lightyellow", edgecolor="gray"))
ax.text(0.65, 0.77, f"Median OS  High: {med_high:.1f} mo", transform=ax.transAxes, fontsize=9, color="#E74C3C")
ax.text(0.65, 0.71, f"Median OS  Low:  {med_low:.1f} mo",  transform=ax.transAxes, fontsize=9, color="#3498DB")

add_at_risk_counts(kmf_high, kmf_low, ax=ax, fontsize=9)
ax.legend(fontsize=11)
plt.tight_layout()
fig.savefig(OUT_DIR / "02_KM_overall_survival.png", dpi=150, bbox_inches="tight")
plt.close()

print(f"  Log-rank p-value  : {lr_os.p_value:.6f}")
print(f"  Test statistic    : {lr_os.test_statistic:.4f}")
print(f"  Median OS (High)  : {med_high:.1f} months")
print(f"  Median OS (Low)   : {med_low:.1f} months")
if lr_os.p_value < 0.05:
    print(f"  ✅ SIGNIFICANT — BCG-High patients have different OS from BCG-Low")
else:
    print(f"  ⚠️  Not significant at p<0.05")
print(f"  ✅ Saved → results/02_KM_overall_survival.png")

# ─────────────────────────────────────────────────────────────
# CELL 8 — Kaplan-Meier: Progression-Free Survival
# ─────────────────────────────────────────────────────────────
print("\n" + "="*65)
print("STEP 5b: Kaplan-Meier — Progression-Free Survival (PFS)")
print("="*65)

fig, ax = plt.subplots(figsize=(8, 6))

kmf_high_pfs = KaplanMeierFitter(label="BCG-High")
kmf_low_pfs  = KaplanMeierFitter(label="BCG-Low")

high_pfs = merged[merged["BCG_GROUP"]=="High"].dropna(subset=["PFS_MONTHS","PFS_EVENT"])
low_pfs  = merged[merged["BCG_GROUP"]=="Low"].dropna( subset=["PFS_MONTHS","PFS_EVENT"])

kmf_high_pfs.fit(high_pfs["PFS_MONTHS"], high_pfs["PFS_EVENT"])
kmf_low_pfs.fit( low_pfs["PFS_MONTHS"],  low_pfs["PFS_EVENT"])

kmf_high_pfs.plot_survival_function(ax=ax, color="#E74C3C", linewidth=2.5, ci_show=True)
kmf_low_pfs.plot_survival_function( ax=ax, color="#3498DB", linewidth=2.5, ci_show=True)

lr_pfs = logrank_test(
    high_pfs["PFS_MONTHS"], low_pfs["PFS_MONTHS"],
    event_observed_A=high_pfs["PFS_EVENT"],
    event_observed_B=low_pfs["PFS_EVENT"]
)

med_high_pfs = kmf_high_pfs.median_survival_time_
med_low_pfs  = kmf_low_pfs.median_survival_time_

ax.set_xlabel("Time (months)", fontsize=12)
ax.set_ylabel("Progression-Free Survival Probability", fontsize=12)
ax.set_title("BCG-HSPC Signature — Progression-Free Survival\nTCGA-BLCA (n=407)", fontsize=12)
ax.set_ylim(0, 1.05)

pval_text = f"Log-rank p = {lr_pfs.p_value:.4f}"
if lr_pfs.p_value < 0.001:
    pval_text = "Log-rank p < 0.001"
ax.text(0.65, 0.85, pval_text, transform=ax.transAxes,
        fontsize=11, fontweight="bold",
        bbox=dict(boxstyle="round,pad=0.3", facecolor="lightyellow", edgecolor="gray"))
ax.text(0.65, 0.77, f"Median PFS High: {med_high_pfs:.1f} mo", transform=ax.transAxes, fontsize=9, color="#E74C3C")
ax.text(0.65, 0.71, f"Median PFS Low:  {med_low_pfs:.1f} mo",  transform=ax.transAxes, fontsize=9, color="#3498DB")

add_at_risk_counts(kmf_high_pfs, kmf_low_pfs, ax=ax, fontsize=9)
ax.legend(fontsize=11)
plt.tight_layout()
fig.savefig(OUT_DIR / "03_KM_PFS.png", dpi=150, bbox_inches="tight")
plt.close()

print(f"  Log-rank p-value  : {lr_pfs.p_value:.6f}")
print(f"  Median PFS (High) : {med_high_pfs:.1f} months")
print(f"  Median PFS (Low)  : {med_low_pfs:.1f} months")
if lr_pfs.p_value < 0.05:
    print(f"  ✅ SIGNIFICANT")
else:
    print(f"  ⚠️  Not significant at p<0.05")
print(f"  ✅ Saved → results/03_KM_PFS.png")

# ─────────────────────────────────────────────────────────────
# CELL 9 — Cox Proportional Hazards Regression
# ─────────────────────────────────────────────────────────────
print("\n" + "="*65)
print("STEP 6: Cox Proportional Hazards Regression")
print("="*65)

from lifelines import CoxPHFitter

# ── Prepare Cox dataframe ────────────────────────────────────
cox_df = merged[[
    "BCG_score", "BCG_GROUP",
    "OS_MONTHS", "OS_EVENT",
    "PFS_MONTHS","PFS_EVENT",
    "AGE", "STAGE_SIMPLE", "SEX"
]].copy()

# Encode categorical variables
cox_df["BCG_HIGH"]     = (cox_df["BCG_GROUP"] == "High").astype(int)
cox_df["STAGE_LATE"]   = (cox_df["STAGE_SIMPLE"] == "Late").astype(int)
cox_df["SEX_MALE"]     = (cox_df["SEX"].astype(str).str.upper() == "MALE").astype(int)
cox_df["AGE_SCALED"]   = (cox_df["AGE"] - cox_df["AGE"].mean()) / cox_df["AGE"].std()

# Drop rows missing any covariate
cox_os_df = cox_df[[
    "OS_MONTHS","OS_EVENT",
    "BCG_HIGH","STAGE_LATE","SEX_MALE","AGE_SCALED"
]].dropna()

cox_pfs_df = cox_df[[
    "PFS_MONTHS","PFS_EVENT",
    "BCG_HIGH","STAGE_LATE","SEX_MALE","AGE_SCALED"
]].dropna()

print(f"  Cox OS  patients : {len(cox_os_df)}")
print(f"  Cox PFS patients : {len(cox_pfs_df)}")

# ── Fit Cox model — OS ────────────────────────────────────────
print("\n── Cox Model: Overall Survival ─────────────────────────────")
cph_os = CoxPHFitter(penalizer=0.1)
cph_os.fit(cox_os_df, duration_col="OS_MONTHS", event_col="OS_EVENT")
cph_os.print_summary(decimals=4)

# ── Fit Cox model — PFS ───────────────────────────────────────
print("\n── Cox Model: Progression-Free Survival ────────────────────")
cph_pfs = CoxPHFitter(penalizer=0.1)
cph_pfs.fit(cox_pfs_df, duration_col="PFS_MONTHS", event_col="PFS_EVENT")
cph_pfs.print_summary(decimals=4)

# ── Extract BCG_HIGH results ───────────────────────────────────
def extract_cox_result(cph, endpoint_name):
    s = cph.summary
    row = s.loc["BCG_HIGH"]
    hr   = np.exp(row["coef"])
    ci_l = np.exp(row["coef lower 95%"])
    ci_u = np.exp(row["coef upper 95%"])
    pval = row["p"]
    print(f"\n  BCG Signature → {endpoint_name}")
    print(f"    HR (95% CI) : {hr:.3f} ({ci_l:.3f} – {ci_u:.3f})")
    print(f"    p-value     : {pval:.6f}")
    if pval < 0.05:
        direction = "PROTECTIVE (High = better survival)" if hr < 1 else "RISK (High = worse survival)"
        print(f"    ✅ SIGNIFICANT — {direction}")
    else:
        print(f"    ⚠️  Not significant (p={pval:.4f})")
    return {"endpoint": endpoint_name, "HR": hr, "CI_low": ci_l, "CI_high": ci_u, "p": pval}

res_os  = extract_cox_result(cph_os,  "Overall Survival")
res_pfs = extract_cox_result(cph_pfs, "Progression-Free Survival")

# ─────────────────────────────────────────────────────────────
# CELL 10 — Forest plot
# ─────────────────────────────────────────────────────────────
print("\n" + "="*65)
print("STEP 7: Forest plot — Cox results")
print("="*65)

def make_forest_plot(cph_os, cph_pfs, save_path):
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    fig.suptitle("Cox Proportional Hazards — BCG-HSPC Signature\nTCGA-BLCA",
                 fontsize=13, fontweight="bold")

    labels = {"BCG_HIGH": "BCG Signature\n(High vs Low)",
              "STAGE_LATE": "Stage\n(Late vs Early)",
              "SEX_MALE":   "Sex\n(Male vs Female)",
              "AGE_SCALED": "Age\n(per SD)"}

    colors = {"BCG_HIGH": "#E74C3C", "STAGE_LATE": "#7F8C8D",
              "SEX_MALE": "#7F8C8D", "AGE_SCALED": "#7F8C8D"}

    for ax, cph, title in [(axes[0], cph_os, "Overall Survival"),
                            (axes[1], cph_pfs, "Progression-Free Survival")]:
        s = cph.summary
        vars_plot = [v for v in ["BCG_HIGH","STAGE_LATE","SEX_MALE","AGE_SCALED"]
                     if v in s.index]
        hrs   = np.exp(s.loc[vars_plot, "coef"]).values
        ci_l  = np.exp(s.loc[vars_plot, "coef lower 95%"]).values
        ci_u  = np.exp(s.loc[vars_plot, "coef upper 95%"]).values
        pvals = s.loc[vars_plot, "p"].values
        y_pos = np.arange(len(vars_plot))

        for i, (var, hr, lo, hi, pv) in enumerate(zip(vars_plot, hrs, ci_l, ci_u, pvals)):
            color = colors.get(var, "#7F8C8D")
            ax.plot([lo, hi], [i, i], color=color, linewidth=2.5)
            ax.scatter(hr, i, color=color, zorder=5,
                       s=120, marker="D" if var=="BCG_HIGH" else "o")
            sig_marker = "**" if pv < 0.01 else ("*" if pv < 0.05 else "")
            ax.text(hi + 0.05, i, f" HR={hr:.2f} {sig_marker}",
                    va="center", fontsize=9, color=color)

        ax.axvline(1.0, color="black", linestyle="--", linewidth=1, alpha=0.6)
        ax.set_yticks(y_pos)
        ax.set_yticklabels([labels.get(v, v) for v in vars_plot], fontsize=10)
        ax.set_xlabel("Hazard Ratio (95% CI)", fontsize=11)
        ax.set_title(title, fontsize=11, fontweight="bold")
        ax.set_xlim(left=0)
        ax.text(0.02, 0.02, "* p<0.05   ** p<0.01",
                transform=ax.transAxes, fontsize=8, color="gray")

    plt.tight_layout()
    fig.savefig(save_path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"  ✅ Forest plot saved → {save_path.name}")

make_forest_plot(cph_os, cph_pfs, OUT_DIR / "04_forest_plot.png")

# ─────────────────────────────────────────────────────────────
# CELL 11 — Summary results table
# ─────────────────────────────────────────────────────────────
print("\n" + "="*65)
print("STEP 8: Final summary")
print("="*65)

summary = pd.DataFrame([
    {
        "Endpoint":     "Overall Survival (OS)",
        "n_patients":   len(cox_os_df),
        "n_events":     int(cox_os_df["OS_EVENT"].sum()),
        "Logrank_p":    lr_os.p_value,
        "Cox_HR":       res_os["HR"],
        "Cox_CI_low":   res_os["CI_low"],
        "Cox_CI_high":  res_os["CI_high"],
        "Cox_p":        res_os["p"],
        "Significant":  res_os["p"] < 0.05,
    },
    {
        "Endpoint":     "Progression-Free Survival (PFS)",
        "n_patients":   len(cox_pfs_df),
        "n_events":     int(cox_pfs_df["PFS_EVENT"].sum()),
        "Logrank_p":    lr_pfs.p_value,
        "Cox_HR":       res_pfs["HR"],
        "Cox_CI_low":   res_pfs["CI_low"],
        "Cox_CI_high":  res_pfs["CI_high"],
        "Cox_p":        res_pfs["p"],
        "Significant":  res_pfs["p"] < 0.05,
    },
])

print(summary.to_string(index=False))
summary.to_csv(OUT_DIR / "05_survival_summary.csv", index=False)

print(f"""
═══════════════════════════════════════════════════════════════
ALL RESULTS SAVED TO: {OUT_DIR}
═══════════════════════════════════════════════════════════════
  01_score_distribution.png  — BCG score histogram + High/Low boxplot
  02_KM_overall_survival.png — Kaplan-Meier OS curve
  03_KM_PFS.png              — Kaplan-Meier PFS curve
  04_forest_plot.png         — Cox HR forest plot (OS + PFS)
  05_survival_summary.csv    — Summary table of all results
  bcg_ssgsea_scores.csv      — Per-patient ssGSEA scores
  merged_scores_clinical.csv — Scores + clinical data merged
  expr_log2_clean.csv.gz     — Cleaned log2 expression matrix

HOW TO INTERPRET:
  If HR < 1 and p < 0.05 for BCG_HIGH → BCG-high patients survive longer
  This means your HSPC reprogramming signature predicts better outcomes
  = clinical translational relevance confirmed
═══════════════════════════════════════════════════════════════
""")

"""#TCGA-BLCA FAILED HERE

Survival analysis only on stage 1/2
"""

# -*- coding: utf-8 -*-
"""
Fixed Stage Subgroup Analysis — TCGA-BLCA
==========================================
Fixes the uppercase "STAGE III" matching bug.
Runs THREE subgroups:
  A) Stage II only         (n~129) — closest to NMIBC
  B) Stage I+II combined   (n~131) — early disease
  C) Non-Stage-IV          (n~271) — excludes only metastatic
"""

from google.colab import drive
drive.mount('/content/drive', force_remount=False)

import pandas as pd
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

from lifelines import KaplanMeierFitter, CoxPHFitter
from lifelines.statistics import logrank_test
from lifelines.plotting import add_at_risk_counts
from pathlib import Path

OUT_DIR = Path("/content/drive/MyDrive/tcga_blca_validation/results")
OUT_DIR.mkdir(parents=True, exist_ok=True)

# ─────────────────────────────────────────────────────────────
# CELL 1 — Load data + fix stage mapping
# ─────────────────────────────────────────────────────────────
merged = pd.read_csv(OUT_DIR / "merged_scores_clinical.csv")
print(f"Total patients: {len(merged)}")

# Show exact raw values first
print("\nRaw AJCC stage values:")
print(merged["AJCC_PATHOLOGIC_TUMOR_STAGE"].value_counts(dropna=False).to_string())

# ── Correct mapping: strip + upper + direct match ─────────────
def map_stage_fixed(val):
    s = str(val).strip().upper()
    if s in ["NAN", "NOT AVAILABLE", "[NOT AVAILABLE]",
             "NOT APPLICABLE", "UNKNOWN", ""]:
        return "Unknown"
    if "STAGE IV"  in s:  return "Stage_IV"
    if "STAGE III" in s:  return "Stage_III"
    if "STAGE II"  in s:  return "Stage_II"
    if "STAGE I"   in s:  return "Stage_I"
    return "Unknown"

merged["STAGE_EXACT"] = merged["AJCC_PATHOLOGIC_TUMOR_STAGE"].apply(map_stage_fixed)

print("\nCorrected stage counts:")
print(merged["STAGE_EXACT"].value_counts(dropna=False).to_string())

# ── Define 3 subgroups ────────────────────────────────────────
subgroups = {
    "StageII_only":   merged[merged["STAGE_EXACT"] == "Stage_II"].copy(),
    "StageI_II":      merged[merged["STAGE_EXACT"].isin(["Stage_I","Stage_II"])].copy(),
    "NonStageIV":     merged[merged["STAGE_EXACT"].isin(["Stage_I","Stage_II","Stage_III"])].copy(),
}

print("\nSubgroup sizes:")
for name, df in subgroups.items():
    print(f"  {name:<20} : {len(df):>3} patients  "
          f"| OS events: {int(df['OS_EVENT'].sum()):>3}  "
          f"| PFS events: {int(df['PFS_EVENT'].sum()):>3}")

# ─────────────────────────────────────────────────────────────
# CELL 2 — KM + Cox for each subgroup
# ─────────────────────────────────────────────────────────────
def run_subgroup_analysis(df, name, out_dir):
    """Run KM (OS+PFS) and Cox for one subgroup. Returns summary dict."""
    print(f"\n{'='*65}")
    print(f"Subgroup: {name}  (n={len(df)})")
    print(f"{'='*65}")

    if len(df) < 20:
        print(f"  ⚠️  Only {len(df)} patients — too few to analyse reliably")
        return None

    # Re-stratify by subgroup median (not full cohort median)
    sub_median = df["BCG_score"].median()
    df = df.copy()
    df["BCG_GROUP"] = np.where(df["BCG_score"] >= sub_median, "High", "Low")
    df["BCG_HIGH"]  = (df["BCG_GROUP"] == "High").astype(int)
    df["SEX_MALE"]  = (df["SEX"].astype(str).str.upper() == "MALE").astype(int)
    df["AGE_SCALED"]= (df["AGE"] - df["AGE"].mean()) / df["AGE"].std()

    n_high = (df["BCG_GROUP"]=="High").sum()
    n_low  = (df["BCG_GROUP"]=="Low").sum()
    print(f"  Median BCG score : {sub_median:.4f}")
    print(f"  BCG-High : {n_high}   BCG-Low : {n_low}")

    results = {"name": name, "n": len(df)}

    fig, axes = plt.subplots(1, 2, figsize=(14, 6))
    fig.suptitle(f"BCG-HSPC Signature — {name}\nTCGA-BLCA",
                 fontsize=13, fontweight="bold")

    # ── KM for OS and PFS ────────────────────────────────────
    for ax, time_col, event_col, label, ep_key in [
        (axes[0], "OS_MONTHS",  "OS_EVENT",  "Overall Survival",          "OS"),
        (axes[1], "PFS_MONTHS", "PFS_EVENT", "Progression-Free Survival", "PFS"),
    ]:
        high_sub = df[df["BCG_GROUP"]=="High"].dropna(subset=[time_col, event_col])
        low_sub  = df[df["BCG_GROUP"]=="Low"].dropna( subset=[time_col, event_col])

        if len(high_sub) < 5 or len(low_sub) < 5:
            ax.text(0.5, 0.5, "Insufficient data",
                    transform=ax.transAxes, ha="center", fontsize=12)
            ax.set_title(label)
            results[f"{ep_key}_p"] = np.nan
            results[f"{ep_key}_med_high"] = np.nan
            results[f"{ep_key}_med_low"]  = np.nan
            continue

        kmf_h = KaplanMeierFitter(label=f"BCG-High (n={len(high_sub)})")
        kmf_l = KaplanMeierFitter(label=f"BCG-Low  (n={len(low_sub)})")
        kmf_h.fit(high_sub[time_col], high_sub[event_col])
        kmf_l.fit(low_sub[time_col],  low_sub[event_col])

        kmf_h.plot_survival_function(ax=ax, color="#E74C3C", linewidth=2.5, ci_show=True)
        kmf_l.plot_survival_function(ax=ax, color="#3498DB", linewidth=2.5, ci_show=True)

        lr = logrank_test(
            high_sub[time_col], low_sub[time_col],
            event_observed_A=high_sub[event_col],
            event_observed_B=low_sub[event_col]
        )

        med_h = kmf_h.median_survival_time_
        med_l = kmf_l.median_survival_time_

        pval_str   = "p < 0.001" if lr.p_value < 0.001 else f"p = {lr.p_value:.4f}"
        box_color  = "#d4edda" if lr.p_value < 0.05 else "#fff3cd"
        ax.text(0.52, 0.88, f"Log-rank {pval_str}",
                transform=ax.transAxes, fontsize=11, fontweight="bold",
                bbox=dict(boxstyle="round,pad=0.3",
                          facecolor=box_color, edgecolor="gray"))
        ax.text(0.52, 0.80, f"Median High: {med_h:.1f} mo",
                transform=ax.transAxes, fontsize=9, color="#E74C3C")
        ax.text(0.52, 0.74, f"Median Low:  {med_l:.1f} mo",
                transform=ax.transAxes, fontsize=9, color="#3498DB")
        ax.set_xlabel("Time (months)", fontsize=11)
        ax.set_ylabel(f"{label} Probability", fontsize=11)
        ax.set_title(label, fontsize=11, fontweight="bold")
        ax.set_ylim(0, 1.05)
        ax.legend(fontsize=9)

        try:
            add_at_risk_counts(kmf_h, kmf_l, ax=ax, fontsize=8)
        except Exception:
            pass

        results[f"{ep_key}_p"]        = lr.p_value
        results[f"{ep_key}_med_high"] = med_h
        results[f"{ep_key}_med_low"]  = med_l

        sig = "✅ SIGNIFICANT" if lr.p_value < 0.05 else "⚠️  Not significant"
        print(f"\n  {label}:")
        print(f"    Log-rank p    : {lr.p_value:.6f}  {sig}")
        print(f"    Median High   : {med_h:.1f} months")
        print(f"    Median Low    : {med_l:.1f} months")
        direction = "BCG-High WORSE ⚠️" if med_h < med_l else "BCG-High BETTER ✅"
        print(f"    Direction     : {direction}")

    plt.tight_layout()
    fname = out_dir / f"KM_{name}.png"
    fig.savefig(fname, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"\n  ✅ Saved → results/KM_{name}.png")

    # ── Cox regression ────────────────────────────────────────
    print(f"\n  Cox regression ({name}):")
    for time_col, event_col, ep_key in [
        ("OS_MONTHS",  "OS_EVENT",  "OS"),
        ("PFS_MONTHS", "PFS_EVENT", "PFS"),
    ]:
        cox_df = df[[time_col, event_col,
                     "BCG_HIGH", "SEX_MALE", "AGE_SCALED"]].dropna()
        n_events = int(cox_df[event_col].sum())

        if n_events < 10:
            print(f"    {ep_key}: only {n_events} events — skip Cox")
            results[f"{ep_key}_HR"]     = np.nan
            results[f"{ep_key}_HR_low"] = np.nan
            results[f"{ep_key}_HR_high"]= np.nan
            results[f"{ep_key}_cox_p"]  = np.nan
            continue

        cph = CoxPHFitter(penalizer=0.1)
        cph.fit(cox_df, duration_col=time_col, event_col=event_col)

        row  = cph.summary.loc["BCG_HIGH"]
        hr   = np.exp(row["coef"])
        ci_l = np.exp(row["coef lower 95%"])
        ci_u = np.exp(row["coef upper 95%"])
        pval = row["p"]

        results[f"{ep_key}_HR"]      = hr
        results[f"{ep_key}_HR_low"]  = ci_l
        results[f"{ep_key}_HR_high"] = ci_u
        results[f"{ep_key}_cox_p"]   = pval

        sig = "✅ SIGNIFICANT" if pval < 0.05 else "⚠️  ns"
        direction = "PROTECTIVE (High=better)" if hr < 1 else "RISK (High=worse)"
        print(f"    {ep_key}: HR={hr:.3f} ({ci_l:.3f}–{ci_u:.3f})  "
              f"p={pval:.4f}  {sig}  → {direction}")

    return results


# ── Run all three subgroups ───────────────────────────────────
all_results = []
for name, df in subgroups.items():
    res = run_subgroup_analysis(df, name, OUT_DIR)
    if res:
        all_results.append(res)

# ─────────────────────────────────────────────────────────────
# CELL 3 — Master summary table
# ─────────────────────────────────────────────────────────────
print("\n" + "="*65)
print("MASTER SUMMARY — All subgroups vs Full cohort")
print("="*65)

# Add full cohort reference row
full_cohort = {
    "name": "Full_cohort",
    "n": 407,
    "OS_p": 0.013959,  "OS_med_high": 26.9, "OS_med_low": 61.4,
    "OS_HR": 1.320,    "OS_HR_low": 1.005,  "OS_HR_high": 1.733,
    "OS_cox_p": 0.046,
    "PFS_p": 0.054051, "PFS_med_high": 22.3,"PFS_med_low": 44.0,
    "PFS_HR": 1.191,   "PFS_HR_low": 0.906, "PFS_HR_high": 1.566,
    "PFS_cox_p": 0.210,
}

print(f"\n{'Subgroup':<22} {'N':>5}  "
      f"{'OS p':>8}  {'OS MedH':>8}  {'OS MedL':>8}  "
      f"{'OS HR':>7}  {'OS Cox p':>9}  "
      f"{'PFS p':>8}  {'PFS HR':>7}  {'PFS Cox p':>9}")
print("-"*105)

def print_row(r, name_key="name"):
    n     = r.get("n", "?")
    os_p  = r.get("OS_p",    np.nan)
    os_mh = r.get("OS_med_high", np.nan)
    os_ml = r.get("OS_med_low",  np.nan)
    os_hr = r.get("OS_HR",   np.nan)
    os_cp = r.get("OS_cox_p",np.nan)
    pfs_p = r.get("PFS_p",   np.nan)
    pfs_hr= r.get("PFS_HR",  np.nan)
    pfs_cp= r.get("PFS_cox_p",np.nan)

    def fmt_p(p):
        if np.isnan(p): return "    —   "
        mark = "✅" if p < 0.05 else "  "
        return f"{mark}{p:.4f}"

    print(f"{r[name_key]:<22} {n:>5}  "
          f"{fmt_p(os_p):>10}  {os_mh:>8.1f}  {os_ml:>8.1f}  "
          f"{os_hr:>7.3f}  {fmt_p(os_cp):>11}  "
          f"{fmt_p(pfs_p):>10}  {pfs_hr:>7.3f}  {fmt_p(pfs_cp):>11}")

print_row(full_cohort)
for r in all_results:
    print_row(r)

# Save summary
summary_df = pd.DataFrame([full_cohort] + all_results)
summary_df.to_csv(OUT_DIR / "08_master_summary.csv", index=False)
print(f"\n✅ Master summary saved → results/08_master_summary.csv")

print(f"""
═══════════════════════════════════════════════════════════════
KEY QUESTION: Does direction flip in any subgroup?
  Full cohort: BCG-High = WORSE survival (HR > 1)
  → If any subgroup shows HR < 1 with p < 0.05:
    BCG signature is PROTECTIVE in that stage subgroup ✅
  → If all subgroups still HR > 1:
    TCGA-BLCA is confirmed wrong cohort for BCG validation
    → Move to IMvigor210 (immunotherapy cohort)
═══════════════════════════════════════════════════════════════
""")